### PR TITLE
Fix(FE) : Ask for confirmation before deleting any dashboard from dashboard list

### PR DESCRIPTION
**Pull request by NishidhJain**
Added antd modal for confirmation before deleting the dashboard and changed the delete from link to button with red color in dashboard list

### CODE REVIEW

**Comment by NishidhJain** [comment]
This solves issue #526.

**Comment by pal-sig** [comment]
Hi @NishidhJain 
Can we integrate a loading state in this delete button then only we trigger the modal state to false

**Comment by NishidhJain** [comment]
@pal-sig you are talking about delete button inside modal, so until the promise is resolved loading should be shown

**Comment by palash-signoz** [comment]
> @pal-sig you are talking about delete button inside modal, so until the promise is resolved loading should be shown

Hi @NishidhJain yes

**Comment by pranay01** [comment]
@NishidhJain Any updates on this PR based on @palash-signoz 's comment?

**Comment by palash-signoz** [comment]
@NishidhJain can you please resolve conflict

**Comment by NishidhJain** [comment]
Hello @palash-signoz @pranay01
Sorry for the late response. I was busy in my work life so was unable reply and do the changes. If anyone can take over the task, please go on. Sorry for the inconvenience.

Thank you

**Comment by pranay01** [comment]
ok. @palash-signoz Please take over this PR and make the necessary fixes

**Review by palash-signoz — APPROVED** [review]

**Pull request merged**
