### PR TITLE
fix: allow workspace blocked users to extend trial

### PR DESCRIPTION
**Pull request by YounixM**
Screenshot 2024-01-18 215138

image

### CODE REVIEW

**Review by Vikrant2520 — APPROVED** [review]

**Review by makeavish — APPROVED** [review]

**Comment by srikanthccv** [comment]
Why aren't _SigNoz URL_ and _Admin Email_ filled? We know only the admin sees this option and we would have their tenant URL. Why not just fill in the details for them?

**Comment by YounixM** [comment]
My bad. I merged it before seeing the comment

**Comment by YounixM** [comment]
@srikanthccv: We want the user to add details to make sure the user has the actual intent to extend and is not just playing around.

**Comment by srikanthccv** [comment]
I think we should generally assume positive intent when it comes to things like this. But it may be fine as is.

**Pull request merged**
