### PR TITLE
chore: form changes

### PR DESCRIPTION
**Pull request by GermaVinsmoke**
part of #2150 

Minor changes related to the form

### CODE REVIEW

**Review by palashgdev — APPROVED** [review]

**Comment by GermaVinsmoke** [comment]
`!orgName` will be handled by the form validation so I think it can be removed from the `isDisabled` condition.

**Comment by GermaVinsmoke** [comment]
Btw, `isLoading` value was used in `disabled` so that the Apply button cannot be clicked again while the request is being sent. Can check the behaviour in Slow 3G.
Now, with your new condition, this thing won't work.

**Comment by palashgdev** [comment]
> `!orgName` will be handled by the form validation so I think it can be removed from the `isDisabled` condition.

yeah updated

**Comment by palashgdev** [comment]
> `!orgName` will be handled by the form validation so I think it can be removed from the `isDisabled` condition.

yeah this is just to add disabled the button

**Review by palashgdev — APPROVED** [review]

**Comment by palashgdev** [comment]
> `!orgName` will be handled by the form validation so I think it can be removed from the `isDisabled` condition.

i think it is good to have as this is already handled via useForm from antd

**Comment by GermaVinsmoke** [comment]
Yeah, it's okay to have it because the same behaviour is there on Signup form also. So, consistency is also needed ✌️

**Pull request merged**
