### PR TITLE
fix(FE): Placeholder for filter traces and incorrect error message in latency filter

### LINKED ISSUE #369: Incorrect error message in Latency filter in trace page
Even when min value is less than max value, the error message on min value is not removed

Expected behavior : If min value is less than max value, then no error message should be shown
min-max

### PR DESCRIPTION
**Pull request by aggmoulik**
Fixes #369 and #381 

Signed-off-by: Moulik Aggarwal <qwertymoulik@gmail.com>

### CODE REVIEW

**Comment by pranay01** [comment]
Thanks @aggmoulik 
@pal-sig Have add you as a reviewer on the PR

**Comment by pranay01** [comment]
@aggmoulik Can you also share a screenshot or quick loom video of how this looks with the PR fixed

**Comment by aggmoulik** [comment]
[LOOM Video](https://www.loom.com/share/2af164f0e8d54d2da7e2027f49795855)

**Comment by pal-sig** [comment]
Hi @aggmoulik 
Can we disable the button until condition are not satisfied ? over the latency modal ?

**Comment by aggmoulik** [comment]
> Hi @aggmoulik Can we disable the button until condition are not satisfied ? over the latency modal ?

What are the conditions for the latency model?

**Comment by pal-sig** [comment]
until min max dependencies are satisfied

**Comment by pal-sig** [comment]
@aggmoulik any update regarding the PR

**Comment by aggmoulik** [comment]
> @aggmoulik any update regarding the PR

Hey @pal-sig Done 👍

**Review by pal-sig — APPROVED** [review]

**Comment by pal-sig** [comment]
@pranay01 can you please confirm the text here

Screenshot 2021-12-13 at 10 04 05 PM

**Comment by pranay01** [comment]
> @pranay01 can you please confirm the text here
> 
> Screenshot 2021-12-13 at 10 04 05 PM

The text is fine, but we don't need error messages to appear below both max and min field at the same time. Only the field which is being edited at the time should show the error value, so that user can fix that

**Comment by pal-sig** [comment]
> > @pranay01 can you please confirm the text here
> > Screenshot 2021-12-13 at 10 04 05 PM
> 
> @pal-sig The text is fine, but we don't need error messages to appear below both max and min field at the same time. Only the field which is being edited at the time should show the error value, so that user can fix that
> 
> Having text appearing below both fields looks awkward

@aggmoulik can you please take a look over this one ?

**Comment by palash-signoz** [comment]
Closing as this is not in the new UI

**Pull request closed without merging**
