### PR TITLE
FE: while saving widget scrolled into view

### PR DESCRIPTION
**Pull request by palashgdev**
Close https://github.com/SigNoz/signoz/issues/3574

after:

https://github.com/SigNoz/signoz/assets/88981777/913fafd3-6c1f-471f-a467-0cbf3e31ba98

before

https://github.com/SigNoz/signoz/assets/88981777/8226a739-b4df-4aab-b0ea-301a66c1fb4a

### CODE REVIEW

**Review by Rajat-Dabade — APPROVED** [review]

**Review by Rajat-Dabade — DISMISSED** [review]
LGTM 🚀

**Comment by srikanthccv** [comment]
I don't this is the right fix. It makes the experience worse because by moving it to the first position you are disturbing their panel organization. Their order contains some meaning to it. The panels are organized in a way that they can see similar panels in the same window view. We shouldn't move the panel to the first position. I think what @ankitnayan is asking is to scroll them to the panel's original position after it is saved so they see the edited panel in the current window view. 

Here is a video to give an idea: https://www.loom.com/share/b9219ac09ff340dda2fd4df602f53d96

**Comment by srikanthccv** [comment]
In general, I think the reviews of frontend changes should be reviewed with user experience in mind.

**Comment by palashgdev** [comment]
blocked over https://github.com/SigNoz/signoz/issues/4081

**Review by YounixM — APPROVED** [review]

**Pull request merged**
