### PR TITLE
feat: FE memory fixes and UX enhancements

### PR DESCRIPTION
**Pull request by pranshuchittora**
Demo 👉🏼  https://youtu.be/yiB2H29suyM

### CODE REVIEW

**Comment by pranay01** [comment]
@pranshuchittora this looks good to me. just confirming - if data is actually 0 ( like 0 RPS) the graph will show 0 right? We are not replacing 0 with no data - right?

**Comment by pranshuchittora** [comment]
> @pranshuchittora this looks good to me. just confirming - if data is actually 0 ( like 0 RPS) the graph will show 0 right? We are not replacing 0 with no data - right?

Yes @pranay01 we will be rendering 0 values

**Review by palash-signoz — CHANGES_REQUESTED** [review]
@pranshuchittora please remove `noDataGraph` props as it is not used anywhere also remove the parent too

**Comment by palash-signoz** [comment]
@pranshuchittora can we center align this text over parent container ?

Screenshot 2022-04-02 at 9 30 28 PM

**Comment by pranshuchittora** [comment]
> @pranshuchittora can we center align this text over parent container ?
> 
> Screenshot 2022-04-02 at 9 30 28 PM

Screenshot 2022-04-05 at 00 09 35

`canvas` is the child of the Card therefore it takes less space. In the above screenshot you can see that the text is in the exact centre of the canvas

**Comment by palash-signoz** [comment]
> 

Probably we can take up in another issue :-D

**Review by palash-signoz — APPROVED** [review]

**Pull request merged**
