### PR TITLE
feat: allow query restrictions for log queries

### LINKED ISSUE #4777: LOGS: Query restrictions
Allow to set query restrictions

### PR DESCRIPTION
**Pull request by nityanandagohain**
Fixes #4777

### CODE REVIEW

**Comment by ankitnayan** [comment]
this will add these restrictions to alerts too, right?

**Comment by nityanandagohain** [comment]
@ankitnayan  yes all select queries for logs as of now.

**Comment by srikanthccv** [comment]
We can get this merged so that you don't have to maintain and build separately.

**Comment by nityanandagohain** [comment]
Yeah  we can merge this, @srikanthccv can you approve it

**Review by srikanthccv — APPROVED** [review]

**Pull request merged**
