### PR TITLE
Fixing Permission problem with volume in wsl

### PR DESCRIPTION
**Pull request by Thorfy**

### CODE REVIEW

**Comment by Thorfy** [comment]
#1866

**Comment by prashant-shahi** [comment]
@Thorfy Thanks for the PR!

Using volumes instead of bind mount will resolve the issue in WSL.

However, it cannot be generic solution at the moment without thorough internal discussion.
As those who would be upgrading in future, will have to run additional steps to migrate from bind mount to volumes.

/cc @ankitnayan

**Comment by JaieParker** [comment]
This fix is very useful for someone doing a first time install like me. Thank you

**Comment by prashant-shahi** [comment]
> Table signoz_traces.distributed_signoz_index_v2 doesn't exist

@JaieParker SigNoz related database and tables are created by SigNoz OtelCollector.
The above issue happens when ClickHouse was not ready at the start time of SigNoz OtelCollectors.

Can you make sure ClickHouse is healthy and then try re-creating SigNoz OtelCollectors?

**Comment by Thorfy** [comment]
> > Table signoz_traces.distributed_signoz_index_v2 doesn't exist
> 
> @JaieParker SigNoz related database and tables are created by SigNoz OtelCollector. The above issue happens when ClickHouse was not ready at the start time of SigNoz OtelCollectors.
> 
> Can you make sure ClickHouse is healthy and then try re-creating SigNoz OtelCollectors?

-> The above issue happens because your folders configuration of clickhouse isn't compatible with windows
@JaieParker cannot recreate clickHouse correctly because clickhouse can't access to the config file 

Using volume in docker composer allow clickhouse to start and configure correctly 
With that, otel collector stop crashing

**Pull request closed without merging**
