### PR TITLE
chore: fixed the typo in user profile picture attribute

### PR DESCRIPTION
**Pull request by indyarocks**
Fixed the typo `ProfilePirctureURL` in `User` attribute

### CODE REVIEW

**Comment by pranay01** [comment]
Nice to see your PR @indyarocks - welcome to SigNoz community :)

**Comment by palashgdev** [comment]
we also have to change in the frontend

**Comment by indyarocks** [comment]
> we also have to change in the frontend

Why? There is no reference of `ProfilePirctureURL` directly anywhere else in the code except these files in the PR.

**Review by srikanthccv — APPROVED** [review]

**Comment by srikanthccv** [comment]
Thanks.

**Pull request merged**
