### PR TITLE
feat: integrate-commitzen

### PR DESCRIPTION
**Pull request by sf-pchakraborty**
Close https://github.com/SigNoz/signoz/issues/913

### CODE REVIEW

**Comment by sf-pchakraborty** [comment]
@palashgdev Please review

**Comment by palashgdev** [comment]
@sf-pchakraborty `git-cz` is not a command

**Comment by palashgdev** [comment]
can you please confirm whether the package is installed or not

**Comment by pranay01** [comment]
@sf-pchakraborty Is this PR no longer relevant? If so, can you close this PR

**Comment by sf-pchakraborty** [comment]
@pranay01 It's still relevant. Sorry parked it for now. Will pick up in a few days again.

**Comment by sf-pchakraborty** [comment]
Hi @palashgdev Can you please review it? Installed the package now.

**Comment by palashgdev** [comment]
> Hi @palashgdev Can you please review it? Installed the package now.

sure @sf-pchakraborty let me check

**Pull request closed without merging**
