### PR TITLE
Adding multi architecture (ARM64 and AMD64) support for signoz components

### PR DESCRIPTION
**Pull request by rajdas98**
Issue- https://github.com/SigNoz/signoz/issues/194

Test Pipeline- https://github.com/rajdas98/signoz/actions/runs/993904482
Screenshot 2021-07-02 at 8 04 45 PM

### CODE REVIEW

**Comment by rahulrana95** [comment]
Can you explain the changes summary @rajdas98

**Comment by rajdas98** [comment]
@rahulrana95 It's in this https://github.com/SigNoz/signoz/issues/194

**Review by rahulrana95 — COMMENTED** [review]
Looks good to me.

**Comment by rajdas98** [comment]
@ankitnayan @pranay01 Can we take this PR?

**Comment by ankitnayan** [comment]
@rajdas98 I am away for a few days. I will review it by the weekend. I hope this is non-blocking.

**Comment by rajdas98** [comment]
No worries @ankitnayan.

**Pull request merged**
