### PR TITLE
feat: lowercase operators support in the where clause is updated

### PR DESCRIPTION
**Pull request by palashgdev**
close https://github.com/SigNoz/signoz/issues/3645

### CODE REVIEW

**Review by nityanandagohain — COMMENTED** [review]
https://github.com/SigNoz/signoz/assets/26831659/a522c891-0a8b-4fd7-b323-6056a93529b6

@palashgdev please check this

**Comment by nityanandagohain** [comment]
https://github.com/SigNoz/signoz/assets/26831659/16f8838d-a8b3-4e50-be3e-1373e1503b51

**Comment by palashgdev** [comment]
> Screen.Recording.2023-10-04.at.11.42.07.AM.mov

i am still working over this one above issue is still not fixed

**Comment by nityanandagohain** [comment]
ohh okay

**Review by nityanandagohain — APPROVED** [review]

**Review by nityanandagohain — APPROVED** [review]
@palashgdev  please create a new issue for supporting update in operators.

**Comment by srikanthccv** [comment]
Can we please spend some time doing some minimum testing? It reflects very poorly on us. I would revert this immediately. I haven't tried anything complicated.

 https://www.loom.com/share/68d339549bf140adb18390d8dcd85ded.

**Comment by nityanandagohain** [comment]
Thanks Srikanth for pointing it out, I mostly checked things related to upercasing and lowercasing. But a lot seems to be missed while testing.

I think for critical parts like this unit tests would have helped right ? @palashgdev @YounixM

**Comment by YounixM** [comment]
Unit tests do help with this and we will be starting to for few flows this week, however, when core functionalities are worked upon, we need to test all the possible flows and then provide signoff. Due to time constraints, we might not be able to add test cases for every possible flow, but we should spend some testing the core functionalities.

I agree with @srikanthccv. Let's revert this PR and fix all bugs around this and then merge.

**Comment by ankitnayan** [comment]
@YounixM if you could enable more devs to add tests easily, we all can chip-in to cover more test cases

**Pull request merged**
