### PR TITLE
Add remove TTL api, and do not allow zero or negative TTL

### LINKED ISSUE #937: Support removal of TTL once set
## Bug description

At the start of a new SigNoz cluster, get TTL API returns `-1` that indicates TTL is not set.
However, once a value is set for TTL. It cannot be unset.
Setting it to `0` makes the SigNoz data _almost_ always unavailable.

## Expected behaviour

Users should be able to unset TTL. It can be either done upon `-1`/`0` duration using the same Set TTL API handler or, we can have a new API handler with the `DELETE` method to achieve the same.

## How to reproduce

- At the start of a new SigNoz, we can see that no TTL is set.
```console
$ curl "localhost:3301/api/v1/settings/ttl"
{"metrics_ttl_duration_hrs":-1,"traces_ttl_duration_hrs":-1}
```

- Now, let's set TTL to any duration
```
$ curl -XPOST "localhost:3301/api/v1/settings/ttl?type=traces;duration=2h"
{"message":"move ttl has been successfully set up"}
```
Now, we are unable to unset any TTL.

## Version information 
* **Signoz version**: `v0.7.4`

## Additional context
Nope.

### LINKED ISSUE #939: Backend should validate TTL values
1. Should be in relevant time unit (hr)
2. Should no allow decimal values
3. What happens when someone set the TTL to 0 (Data will never be retained)

### PR DESCRIPTION
**Pull request by srikanthccv**
Fixes #937
Fixes #939

### CODE REVIEW

**Review by ahsanbarkati — DISMISSED** [review]
LGTM

**Review by prashant-shahi — DISMISSED** [review]
:shipit: LGTM

In another PR we should also address the scenario when the user wants to remove cold storage while keeping TTL intact.

**Comment by srikanthccv** [comment]
This is ready to be reviewed again

**Comment by ankitnayan** [comment]
@srikanthccv how does it work with big data? Should we make this async like we are planning to do for setTTL?

**Review by ankitnayan — APPROVED** [review]

**Pull request merged**
