### PR TITLE
Feat: baseEnd point is added

### PR DESCRIPTION
**Pull request by palashgdev**
Close https://github.com/SigNoz/signoz/issues/357 baseEnd point is added

### CODE REVIEW

**Comment by pranshuchittora** [comment]
- https://grafana.com/tutorials/run-grafana-behind-a-proxy/
- https://github.com/grafana/grafana/issues/4305#issuecomment-194183103

**Comment by palash-signoz** [comment]
just add this env `FRONTEND_BASE` this will serve whole frontend with this base path

**Review by pranshuchittora — COMMENTED** [review]
@prashant-shahi you are the right person to review this.

**Comment by prashant-shahi** [comment]
@pranshuchittora Already reviewed and given my feedback to @palash-signoz

**Comment by luolong** [comment]
This has not been merged to the develop branch?

**Comment by tirthesh-bohra** [comment]
Any ideas on how we can configure FRONTEND_PATH with Helm charts?

**Pull request closed without merging**
