### PR TITLE
feat: added logs and traces tab in host metrics detail view

### PR DESCRIPTION
**Pull request by rahulkeswani101**
#### Screenshots

image

#### Affected Areas and Manually Tested Areas

----

> [!IMPORTANT]
> Add logs and traces tabs to host metrics detail view with new components, styles, and utilities.
> 
>   - **Behavior**:
>     - Add `HostMetricLogsDetailedView` and `HostMetricTraces` components for logs and traces in host metrics detail view.
>     - Integrate components into `HostMetricDetail` for view switching.
>     - Add `isModalTimeSelection` prop to `HostDetailProps` and `DateTimeSelectionV2` for modal time selection.
>   - **Styles**:
>     - Add styles for `HostMetricTraces` in `HostMetricTraces.styles.scss`.
>     - Update styles in `InfraMonitoring.styles.scss` for better layout and design.
>   - **Utilities**:
>     - Add `formatNanoToMS` utility in `utils.ts` for duration formatting.
>     - Add `getHostTracesQueryPayload` and `getHostLogsQueryPayload` in `constants.ts` for query payloads.
>   - **Misc**:
>     - Update `HostsList.tsx` to use new `HostMetricDetail` with logs and traces.
>     - Modify `DateTimeSelectionV2` to support modal time selection.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=SigNoz%2Fsignoz&utm_source=github&utm_medium=referral)<sup> for c452ce9dde41ff30e0c91cadced509bdcba81638. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by srikanthccv** [comment]
List view testing - https://www.loom.com/share/daf25a3c66874aca98018de9052c1fd3
Detail view testing - https://www.loom.com/share/dc10f2ed13784e37b540fc5280a0fdc3

**Comment by GeekBoySupreme** [comment]
@rahulkeswani101 can we move the pagination to the bottom of the table?

**Comment by srikanthccv** [comment]
@GeekBoySupreme are you referring to the traces tab in detail view? We are taking the same component from traces explorer.

**Comment by srikanthccv** [comment]
@rahulkeswani101 traces tabs issues https://www.loom.com/share/ddb69fafe8f0468d867c0f412b971690

- Clicking on the item should open in trace detail page.
- There should be a way to go to the Explorer page from the traces tab and logs tab to trace explorer and log explorer respectively.
- There is weird loading issue when adding filters and moving pages

**Pull request merged**
