### PR TITLE
fix: onRun Query offset is made zero

### PR DESCRIPTION
**Pull request by palashgdev**
before: https://www.loom.com/share/bf00b7edf24845f39761c74d55677f00?sid=2ee60b28-1abb-43c1-9c90-08bf8313009b

after: 

https://github.com/SigNoz/signoz/assets/88981777/a709b3c5-cd14-49cc-850e-9abe7ecabc29

Close https://github.com/SigNoz/engineering-pod/issues/1110

### CODE REVIEW

**Comment by srikanthccv** [comment]
Does the same happen in logs explorer?

**Comment by palashgdev** [comment]
> Does the same happen in logs explorer?

yes this was the same behaviour under logs explorer also

**Comment by srikanthccv** [comment]
Please fix in both the explorer pages.

**Comment by palashgdev** [comment]
> Please fix in both the explorer pages.

@srikanthccv i have fixed in both the pages

**Review by srikanthccv — APPROVED** [review]
This change also resets the page size but that maybe fine.

**Review by Rajat-Dabade — DISMISSED** [review]

**Comment by YounixM** [comment]
image


the same issue exists in old trace explorer as well. getFilteredSpans doesn't reset offset on run Query

**Comment by palashgdev** [comment]
> image
> 
> the same issue exists in old trace explorer as well. getFilteredSpans doesn't reset offset on run Query

this pr is only targeting for new trace explorer and logs explorer

**Review by srikanthccv — APPROVED** [review]
I tested this on the new explorer pages and approving those changes.

**Review by Rajat-Dabade — DISMISSED** [review]

**Comment by palashgdev** [comment]
@YounixM can you also verify this one ?

**Review by makeavish — COMMENTED** [review]
Page size should not be reset on Run Query, it can be annoying for user

**Comment by srikanthccv** [comment]
@palashgdev This commit added the limit part https://github.com/SigNoz/signoz/pull/4083/commits/5205610b2bbadb56be62dc03282cf2fa7828df25. The concern expressed by @makeavish is about the page size. My understanding is that they (limit and pageSize) are different. Does it fix the issue? 

@makeavish Please review again.

**Review by makeavish — APPROVED** [review]

**Comment by srikanthccv** [comment]
There is no prev/next page since logs is an infinite scroll. I tested the logs explorer. When you go back and apply a new filter the offset is reset.

**Comment by srikanthccv** [comment]
@YounixM please review and merge.

**Comment by YounixM** [comment]
Sure @srikanthccv. Have an open question in the PR. will approve and merge post that.

**Comment by srikanthccv** [comment]
@YounixM is this the open question you refer to https://github.com/SigNoz/signoz/pull/4083#issuecomment-1829225447? I think the old explorer can be addressed independently.

**Review by YounixM — APPROVED** [review]

**Comment by YounixM** [comment]
It was related to the logic. We can take it up later. Have approved the PR. 

@srikanthccv @Rajat-Dabade: Please approve. We can merge it post.

**Review by makeavish — APPROVED** [review]

**Review by srikanthccv — APPROVED** [review]

**Pull request merged**
