### PR TITLE
fix(FE): remove refresh of graph on expanding and closing trace panel

### PR DESCRIPTION
**Pull request by hussamkhatib**
https://www.loom.com/share/4ebf43530bd841118905fdbae7891652

fixes: #775

### CODE REVIEW

**Comment by palashgdev** [comment]
Hello, @hussamkhatib.
can you check if your current action is causing a problem retrieving the next set of filters?

**Comment by makeavish** [comment]
@hussamkhatib Right now when panel is closed then the filters are not ignored so there is inconsistency.
@palashgdev Either API call should not be made or filters should be ignored on closing panel, please take a call on this.

**Comment by YounixM** [comment]
Stale / Inactive PR. Closing it for now.

**Comment by YounixM** [comment]
Stale / Inactive PR. Closing it for now.

**Pull request closed without merging**
