### PR TITLE
Fix for running signoz-schema-migrator under docker-swarm

### PR DESCRIPTION
**Pull request by Ruppsn**
Fixes: https://github.com/SigNoz/signoz/issues/6477

----

> [!IMPORTANT]
> Add `sync` and `--up=` arguments to `otel-collector-migrator` in `docker-compose.yaml` for Docker Swarm compatibility.
> 
>   - **Behavior**:
>     - Add `sync` and `--up=` arguments to `otel-collector-migrator` service in `docker-compose.yaml` to ensure proper execution under Docker Swarm.
>   - **Misc**:
>     - No changes to other services or files.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=SigNoz%2Fsignoz&utm_source=github&utm_medium=referral)<sup> for 0cc22df1db668e07909b4757468114abc79aa6cf. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by prashant-shahi** [comment]
Both `sync` and `async` schema migrators are needed.
And the `async` must run after the `sync` is successfully executed.

In Docker Compose, we achieved this using `depends_on.<service-name>.condition`:

```yaml
depends_on:
      otel-collector-migrator-sync:
        condition: service_completed_successfully
```

However, this exact behaviour will not supported in Docker Swarm.
We will need to compromise for some other solution which achieves this behavior.

Ref: https://github.com/docker/cli/issues/3880

**Comment by Ruppsn** [comment]
Does this mean that meanwhile docker swarm will not be runnable with signoz?

**Comment by dieterblancke** [comment]
Wouldn't it then be better to change the migrator to run both (first sync, then async) migrations instead of spawning different containers for it?

**Comment by prashant-shahi** [comment]
> Does this mean that meanwhile docker swarm will not be runnable with signoz?

With your PR changes, it should work fine for now as we do not have any async migrations yet.

Though after we include async migrations, we may need to spawn async migrations post install manually for swarm.

**Comment by dieterblancke** [comment]
> > Wouldn't it then be better to change the migrator to run both (first sync, then async) migrations instead of spawning different containers for it?
> 
> Technically, we could do that as well. But it's best to separate these two for the ease of running only either of them when needed.
> 
> @srikanthccv any thoughts here?

Could still do it as it works now and accept both "sync" and "async" commands, and if both are present make sure it executes in the order of "first sync, then async".

I'm not sure as to how easy/hard that would be to achieve as I haven't gotten the time to look into how the migrator service works but in my head it sounds like it should be possible.

**Review by srikanthccv — APPROVED** [review]
Will address async in seperate PR

**Pull request merged**
