### PR TITLE
feat: added helper text, learn-more and doc-link

### PR DESCRIPTION
**Pull request by SagarRajput-7**
#### Screenshots

Screenshot 2024-05-17 at 4 09 39 PM
Screenshot 2024-05-17 at 4 09 44 PM

Screenshot 2024-05-20 at 10 34 37 PM
Screenshot 2024-05-20 at 10 34 43 PM
Screenshot 2024-05-20 at 11 49 39 PM

image

image

Screenshot 2024-05-21 at 7 05 55 PM
Screenshot 2024-05-21 at 7 13 04 PM

image

### CODE REVIEW

**Review by Vikrant2520 — COMMENTED** [review]
we need `Learn More here` with here being the link? or `Learn More` being the link itself ?

**Comment by makeavish** [comment]
> we need `Learn More here` with here being the link? or `Learn More` being the link itself ?

We just need Learn More being the link itself

**Comment by SagarRajput-7** [comment]
> > we need `Learn More here` with here being the link? or `Learn More` being the link itself ?
> 
> We just need Learn More being the link itself

please check this - 
image

its seems better to me - @Vikrant2520 @makeavish

**Comment by Vikrant2520** [comment]
> > > we need `Learn More here` with here being the link? or `Learn More` being the link itself ?
> > 
> > 
> > We just need Learn More being the link itself
> 
> please check this - image
> 
> its seems better to me - @Vikrant2520 @makeavish

the `here` still seems redundant. we can just highlight the module name itself

**Comment by Vikrant2520** [comment]
also build is failing

**Review by makeavish — APPROVED** [review]

**Comment by Vikrant2520** [comment]
image
`this will persist across tab change here` ? what does this mean ?

**Comment by YounixM** [comment]
@SagarRajput-7: You can pick up the text changes later. Merging for now

**Review by YounixM — APPROVED** [review]

**Pull request merged**
