### PR TITLE
Enhancement for Save View PRD.

### PR DESCRIPTION
**Pull request by Rajat-Dabade**
Implemented search options in dropdown.
All the review changes in this PR: https://github.com/SigNoz/signoz/pull/3404

Loom: https://www.loom.com/share/eeffdf157e48401aa2d7fb1d0283ddad?sid=6efd87d9-28e0-478e-80e2-26b01844958d

Close https://github.com/SigNoz/signoz/issues/1958

### CODE REVIEW

**Comment by pranay01** [comment]
@Rajat-Dabade @YounixM I had some feedback which would be great to be incorporated in this PR 

https://www.loom.com/share/e6b60368706f49ae8f77c7d2eee19df1?sid=2b211953-8534-4904-a27e-3c86d92adaf5

**Comment by srikanthccv** [comment]
The search seems to be working. Please incorporate Pranay's feedback and also look into this https://www.loom.com/share/45e497046d034245907fcfa6fd2f6abf

**Review by srikanthccv — APPROVED** [review]
Tested search and reset functionality.

**Comment by srikanthccv** [comment]
@palashgdev please review and merge.

**Comment by palashgdev** [comment]
> @palashgdev please review and merge.

@srikanthccv few points are yet to address 

https://github.com/SigNoz/signoz/pull/3480#issuecomment-1711301258

**Review by palashgdev — APPROVED** [review]

**Comment by srikanthccv** [comment]
Yes, let's get that comment addressed there.

**Pull request merged**
