### PR TITLE
fix: added pointer property on header dropdowns

### PR DESCRIPTION
**Pull request by Chakravarthy7102**
I made a small CSS change to improve the user experience . Now, when users hover over dropdown elements on the header, the cursor changes to a pointer. This visual cue helps users identify interactive elements and enhances the usability of the website.

### CODE REVIEW

**Comment by palashgdev** [comment]
don't use inline style use styled component for same

**Comment by Chakravarthy7102** [comment]
> don't use inline style use styled component for same

Hi @palashgdev , `<Space/>` is a Antd component and this is the one way of styling with two options and css classes, 
and from your comment I belive you are suggesting to extend `<Space/>` with styled component and apply style to it in the following way.

```typescript

import type { Space } from 'antd';
import styled from 'styled-components';

const Space: React.FC<ButtonProps> = styled(Space)`
  cursor: pointer;
`;

```
Please correct me If I'm wrong.

**Comment by palashgdev** [comment]
> > don't use inline style use styled component for same
> 
> Hi @palashgdev , `<Space/>` is a Antd component and this is the one way of styling with two options options available, and from your comment I belive you are suggesting to extend `<Space/>` with styled component and apply style to it in the following way.
> 
> ```ts
> import type { Space } from 'antd';
> import styled from 'styled-components';
> 
> const Space: React.FC<ButtonProps> = styled(Space)`
>   cursor: pointer;
> `;
> ```
> 
> Please correct me If I'm wrong.

don't use react.fc also more info https://github.com/facebook/create-react-app/pull/8177

**Comment by Chakravarthy7102** [comment]
> > > don't use inline style use styled component for same
> > 
> > 
> > Hi @palashgdev , `<Space/>` is a Antd component and this is the one way of styling with two options options available, and from your comment I belive you are suggesting to extend `<Space/>` with styled component and apply style to it in the following way.
> > ```ts
> > import type { Space } from 'antd';
> > import styled from 'styled-components';
> > 
> > const Space: React.FC<ButtonProps> = styled(Space)`
> >   cursor: pointer;
> > `;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please correct me If I'm wrong.
> 
> don't use react.fc also more info [facebook/create-react-app#8177](https://github.com/facebook/create-react-app/pull/8177)

hey @palashgdev, I incorporated your suggested changes back then. please have a look

**Pull request closed without merging**
