### PR TITLE
fix: added logic to keep sections uncollapsed for all filtered items

### PR DESCRIPTION
**Pull request by SagarRajput-7**
#### Related Issues / PR's

https://github.com/SigNoz/engineering-pod/issues/1422

#### Screenshots

https://github.com/SigNoz/signoz/assets/162284829/aae4b882-0531-4945-b8ec-19a71ddad86c

### CODE REVIEW

**Comment by SagarRajput-7** [comment]
Added test case for this here - https://github.com/SigNoz/signoz/pull/5451

specifically - `should render the trace filter with the given query`

**Comment by YounixM** [comment]
@SagarRajput-7 : Where are we stored the opened sections?

**Comment by SagarRajput-7** [comment]
> @SagarRajput-7 : Where are we stored the opened sections?

We don't store the opened sections (except the default one `'hasError', 'durationNano', 'serviceName'`).  We are in sync with compositeQuery and rely on it for the section's state. So if a filter is added from a particular section then for better usability we will be keeping that section open by default.

**Comment by YounixM** [comment]
Does it maintain the state on hard refresh?

**Comment by SagarRajput-7** [comment]
> Does it maintain the state on hard refresh?

Yes

**Review by YounixM — APPROVED** [review]

**Pull request merged**
