### PR TITLE
docker setup: docker compose without testing app

### PR DESCRIPTION
**Pull request by szobov**
### Summary

Hey there,

Thanks for making such an excellent self-hosted traceability platform! :muscle: 

I wanted to adopt SigNoz, but I faced an issue because I needed to use a vendor docker-compose file when I didn't need a test application.

Current documentation [proposes](https://signoz.io/docs/operate/docker-standalone/#remove-the-sample-application-from-signoz-dashboard) commenting out these services in `docker-compose.yaml`.

Since docker-compose [supports](https://docs.docker.com/compose/multiple-compose-files/include/) `include` command, we can overcome the need to edit existing code and also remove code duplication :hocho: 

I preserved the existing interfaces, so:
`docker compose -f docker/clickhouse-setup/docker-compose.yaml up -d`,  would run the same set of services (with the testing app).

The interface that was added is:
`docker compose -f docker/clickhouse-setup/docker-compose-minimal.yaml up -d`, which won't run testing app.

Please let me know if you like it, and then I can update the documentation.
I'm looking forward to your comments!

### CODE REVIEW

**Review by prashant-shahi — DISMISSED** [review]

**Comment by grandwizard28** [comment]
Hi @szobov,
Thanks for opening a PR here! Can you please resolve the merge conflicts?

**Comment by szobov** [comment]
Hey @grandwizard28 
Thanks for your comment.
I'll resolve conflicts now, but it's very unfortunate that it took so long to get your attention.
Solving such conflicts is a bit painful because I'm not constantly following all the updates in this repo, and now I have to make sure that I don't miss anything due to conflict resolution.
I hope you can give this PR a little bit more attention after I solve the merge conflicts.
Thanks :pray:

**Review by therealpandey — APPROVED** [review]

**Comment by grandwizard28** [comment]
Hey @szobov,
This looks good!

You can proceed with updating the documentation here: https://signoz.io/docs/operate/docker-standalone/#remove-the-sample-application-from-signoz-dashboard

**Review by prashant-shahi — APPROVED** [review]

**Comment by szobov** [comment]
Hey @grandwizard28 

Thanks for the heads up!
I created a PR with documentation changes and linked it to this one.
Could you please have a look :pray: 
Many thanks.

**Pull request merged**
