### PR TITLE
feat: version page is added

### LINKED ISSUE #827: SigNoz version number and system status within the dashboards/UI
Currently, SigNoz version number only appears in the Sign Up page. It is not shown within the UI anywhere after that.

It would be good to understand for users which version they are on, so that they can upgrade when new version is released or even use this to raise Github issues etc.

### PR DESCRIPTION
**Pull request by palash-signoz**
Close #827

### CODE REVIEW

**Review by pranshuchittora — CHANGES_REQUESTED** [review]
⚠️ FE is working in dev only, not working in prod build. Try building it and running it locally.

Screenshot 2022-03-29 at 17 24 54

---

### Some review comments as per the dev build

Can you try to resolve this warning
Screenshot 2022-03-29 at 17 18 40

--- 

Version number is not visible when the sidenav is collapsed

https://user-images.githubusercontent.com/32242596/160604928-7f68c6cd-7198-4e40-b942-4ef8361b7d93.mov

--- 

Also can we show some message like 
```
✅  You are running the latest version of SigNoz.
```
As there's no visual feedback to the user regarding the version

Screenshot 2022-03-29 at 17 21 16

**Comment by pranay01** [comment]
Thanks for the notes @pranshuchittora Have updated the designs a bit

If user is on latest version
https://www.figma.com/file/lE5BDDuulXuGnqvB5GRk1V/SigNoz-OSS---v2-Designs?node-id=2290%3A36312

If user is not on latest version
https://www.figma.com/file/lE5BDDuulXuGnqvB5GRk1V/SigNoz-OSS---v2-Designs?node-id=2422%3A37051

@palash-signoz Lets show a icon in the left side panel also.
- warning sign icon if user is not on the latest version

- tick icon in green if user is on the latest version

The icon should be shown in left panel on collapsing the left side panel also ( like slack icon for support)

I have also added a message if user is not on latest version

**Comment by pranay01** [comment]
@palash-signoz How can I test this for an older version of SigNoz so that I can see what is shown in that case?

**Comment by pranshuchittora** [comment]
https://user-images.githubusercontent.com/32242596/161242972-1bb003c2-577a-40a2-83cd-f4e6ae30f80a.mov

**Comment by pranshuchittora** [comment]
@palash-signoz when the API request fails then the message is shown as you are on older version, which is not totally correct because it is possible that the user is under a protected network where making such request is not possible. Let's show some relevant message over here. Let's confirm the same with the product team to avoid any divergence. 


Screenshot 2022-04-01 at 17 49 34

---
Why this is not working any idea ?

https://user-images.githubusercontent.com/32242596/161262871-c18873c8-33d0-46a8-ba62-e33b5ead43bd.mov

**Comment by pranshuchittora** [comment]
## 1. 

Looks like the BE is returning commit tag not the exact version. @ankitnayan it is highly likely that some users can run this from some branch or a particular commit in that case we must define the version in some file (not read from git if we are doing so)
Screenshot 2022-04-05 at 13 22 06


--- 

## 2.

IMO @palash-signoz when the API break then in that case we must show the current version in the sidebar. 

Screenshot 2022-04-05 at 13 22 51

**Comment by ankitnayan** [comment]
> ## 1.
> Looks like the BE is returning commit tag not the exact version. @ankitnayan it is highly likely that some users can run this from some branch or a particular commit in that case we must define the version in some file (not read from git if we are doing so) Screenshot 2022-04-05 at 13 22 06
> 
> ## 2.
> IMO @palash-signoz when the API break then in that case we must show the current version in the sidebar.
> 
> Screenshot 2022-04-05 at 13 22 51

this will ideally show version for releases done by signoz. Developers would ideally see commit hash. Also, the version is automatically injected to query-service during build based on tags or commits. 

I think this will work fine for all users running via docker-compose or helm, right?

**Review by pranshuchittora — APPROVED** [review]
LGTM Working as expected
Screenshot 2022-04-05 at 18 20 50

**Pull request merged**
