### PR TITLE
feat: [GH-3645]: case insensitive operators for query builder

### PR DESCRIPTION
**Pull request by vikrantgupta25**
### Summary

- updated the tag regex to match the `case-insensitive` operators and convert them in upper case as the entire codebase handling depends on the same. 
- this takes care of suggestions and query

#### Related Issues / PR's

This solves #3645 

#### Screenshots

NA

### CODE REVIEW

**Comment by palashgdev** [comment]
suggested options are still in upper case can you please confirm ?

**Comment by Vikrant2520** [comment]
@palashgdev the recommendations for operators should be uni-case as that is the standard format , as soon as we enter case insensitive operator then the further recommendations work as expected.  CC :- @nityanandagohain

**Comment by palashgdev** [comment]
ok then can you please confirm this one 

https://github.com/SigNoz/signoz/assets/88981777/8f7dfa95-8b14-469c-8975-d1d7f49c1166

**Review by nityanandagohain — CHANGES_REQUESTED** [review]
* Whenver we select an  operator like `=` from the UI the value suggestion is not working, screenshot attached.
* Found the same issue as palash reported, we can maybe suggest values for not symbolic operators only after space is added.
image

**Comment by Vikrant2520** [comment]
@nityanandagohain i have addressed the first issue you posted, discussing about the second in the channel

**Pull request closed without merging**
