### PR TITLE
feat: add the list view for the traces explorer 

### PR DESCRIPTION
**Pull request by dnazarenkoo**
Close - [2333](https://github.com/SigNoz/signoz/issues/2333)

### CODE REVIEW

**Comment by makeavish** [comment]
In list view PR, when we switch from list view to time series view then two query range API calls are made.
Can you please check that?
@dnazarenkosignoz

**Comment by dnazarenkoo** [comment]
> In list view PR, when we switch from list view to time series view then two query range API calls are made. Can you please check that? @dnazarenkosignoz

@makeavish fixed

**Comment by makeavish** [comment]
In list view there should also be option for 10/page, and set it as default
Screenshot 2023-06-27 at 20 35 39

**Comment by makeavish** [comment]
The list view row should be clickable and link to trace details page.
@dnazarenkoo 
cc: @palashgdev

**Comment by makeavish** [comment]
@dnazarenkoo When there's an error from list view backend API then the frontend is stuck on loading.

**Comment by makeavish** [comment]
@dnazarenkoo Boolean columns are not handled.
Example: hasError when false should be showing false instead of N/A, similarly should show true when true instead of empty value which is being shown currently.
Screenshot 2023-07-03 at 17 05 10

**Comment by makeavish** [comment]
When number is 0 (zero) then show zero instead of N/A
@dnazarenkoo

**Comment by makeavish** [comment]
When a user selects spanID then show `spanID`, similarly for `parentSpanID`, `traceID`.
Screenshot 2023-07-03 at 17 11 16

**Comment by makeavish** [comment]
@dnazarenkoo Found another issue. 
https://share.vidyard.com/watch/rHKWAW2MNCzBVtxeF8BQfd?

For this you can create a separate PR and merge this PR after conflicts are resolved.

**Comment by makeavish** [comment]
Date column is shown wrong and we can't expand the view as well

Screenshot 2023-07-04 at 12 24 37

**Comment by makeavish** [comment]
Columns which are already added to column shouldn't be shown in add a column list.

Screenshot 2023-07-04 at 12 27 38

**Comment by makeavish** [comment]
Aggregate Attribute should be disabled in list view. 
Currently user is able to write text in the field and API is also called.

Screenshot 2023-07-04 at 12 38 01

**Comment by makeavish** [comment]
Hide legend in list and traces view.

Screenshot 2023-07-04 at 12 39 34

**Comment by makeavish** [comment]
Hide aggregate every in list view.

Screenshot 2023-07-04 at 12 40 35

**Review by makeavish — DISMISSED** [review]
LGTM, apart from the issues mentioned.
Pending issues can be solved in separate PRs.

**Comment by makeavish** [comment]
Sort by `timestamp desc` by default, similar to logs list view.

**Review by makeavish — APPROVED** [review]

**Review by palashgdev — APPROVED** [review]

**Pull request merged**
