### PR TITLE
fix: add support for {max/min/avg} of rate

### LINKED ISSUE #2913: Support `Avg_rate`, `Max_rate`, `Min_rate` in query builder
In Query builder `Avg_rate`, `Max_rate`, `Min_rate` are not supported currently

### PR DESCRIPTION
**Pull request by srikanthccv**
Fixes #2913

### CODE REVIEW

**Review by makeavish — APPROVED** [review]
This PR LGTM.
Can you also update frontend labels to Avg Rate, Max Rate and Min Rate?

**Review by nityanandagohain — APPROVED** [review]

**Comment by srikanthccv** [comment]
Do you find Avg Rate, Max Rate and Min Rate or capitalised AVG_RATE, `MAX_RATE`, `MIN_RATE` to be more appropriate? I think having `_` make a clear distinction between two aggregations.

**Comment by srikanthccv** [comment]
I am merging, the label change will be addressed if there is need.

**Comment by makeavish** [comment]
> Do you find Avg Rate, Max Rate and Min Rate or capitalised AVG_RATE, `MAX_RATE`, `MIN_RATE` to be more appropriate? I think having `_` make a clear distinction between two aggregations.
I also feel that `MAX_RATE` capitalized with `_` is better.

**Pull request merged**
