### PR TITLE
feat: data time, UI and graph label consistency across FE

### LINKED ISSUE #848: Inconsistent date formats on trace filter page
The filter on the top right corner has date in `YYYY/MM/DD` format. While in the spans table it is in `DD/MM/YYYY` format

inconsistent_date_formats

### PR DESCRIPTION
**Pull request by pranshuchittora**
Closes #848 #864 #849

**Changes via this PR**
- Add Y-Axis unit for remaining Metrics Graphs
- Consistent data and time format on Trace Filter Page
- Horizontal scrolling on Trace Filter page while interacting with the SideNav.
- 🌟  Persistent sidenav collapse state (just like Dark Mode)
- Remove unit name from Graph Labels

### CODE REVIEW

**Comment by ankitnayan** [comment]
@pranshuchittora I think we missed adding default units at a few places:
- External Call RPS(by Address)
- Database Calls RPS
- Database Calls Avg Duration

**Comment by palash-signoz** [comment]
> @pranshuchittora I think we missed adding default units at a few places:
> 
> * External Call RPS(by Address)
> * Database Calls RPS
> * Database Calls Avg Duration

@ankitnayan for it is added in RPS => https://github.com/SigNoz/signoz/blob/241398408ae27f6b7ec6501a2d6f78eedf41b59a/frontend/src/container/MetricsApplication/Tabs/Application.tsx#L193

**Comment by pranshuchittora** [comment]
Demo of the PR

https://user-images.githubusercontent.com/32242596/159430783-c49898f1-2444-44cd-bde0-e74fa425b559.mov

**Comment by pranshuchittora** [comment]
Demo of the PR
https://user-images.githubusercontent.com/32242596/159432711-d5594b33-b508-48c9-bc0a-662f1ada1f70.mp4

**Comment by pranshuchittora** [comment]
Demo
https://user-images.githubusercontent.com/32242596/159432711-d5594b33-b508-48c9-bc0a-662f1ada1f70.mp4

**Review by palash-signoz — APPROVED** [review]

**Comment by palash-signoz** [comment]
UI LTGM but let @ankitnayan confirm node version bump change

**Pull request merged**
