### PR TITLE
feat: added support for filterBy in trace tab such as filterBy spanCount

### PR DESCRIPTION
**Pull request by eKuG**
### Summary

Solves #3174 

#### Screenshots

NA

#### Affected Areas and Manually Tested Areas

----

> [!IMPORTANT]
> Add support for filtering trace queries by `spanCount` using a new `filterBy` parameter in query functions.
> 
>   - **Behavior**:
>     - Added `filterBy` parameter to `runBuilderQuery()` in `helper.go` and `v2/helper.go` to support filtering by `spanCount`.
>     - Updated `PrepareTracesQuery()` in `query_builder.go` and `traces/v3/query_builder.go` to accept `filterBy` and incorporate it into query construction.
>   - **Models**:
>     - Added `FilterBy` field to `QueryRangeParamsV3` in `v3.go` to store filter criteria.
>   - **Functions**:
>     - Modified `buildTracesQuery()` in `traces/v3/query_builder.go` to handle `filterBy` parameter.
>   - **Misc**:
>     - Updated function signatures for trace query preparation to include `filterBy` in `query_builder.go` and `traces/v3/query_builder.go`.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=SigNoz%2Fsignoz&utm_source=github&utm_medium=referral)<sup> for fd3160526db3772a3d5df04ae2d7621d3df26656. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by srikanthccv** [comment]
@eKuG I see two issues with this change.

1. `... GROUP BY traceID  ...`

This is not going to work at scale. We can't do a group by a very high cardinal column at query. The number of traces can go from a few tens of millions to several hundred million and billions easily. Adding such a column in a group by is not an option because there won't be enough memory. Did you test this on a few billion traces or several hundred million traces at least? 

2. FilterBy string in the request payload

I would assume the capability should support the ability to specify the span count in the request, for example, give me traces with span count > 1000 and < 2000. I don't see how that's supported.

**Comment by eKuG** [comment]
Hey @srikanthccv Lets talk about the second point first.
So "filterBy" is an attribute used to filter traces by either span_count or trace_duration. It has no other purpose. (In hindsight, I think I should rename thiss column to something like "trace_filter"). Let me know what you think.
If we need to finf the traces where 1000<spanCount<2000, that will go in the where clause. 

My final query was looking something like this. So the span_count > x will be present in the where clause with the timestamp.

```
SELECT
    traceID,
    COUNT() AS span_count,
    max(toInt64(timestamp) + durationNano) - min(toInt64(timestamp)) AS total_duration_nano
FROM signoz_traces.signoz_index_v2
WHERE (timestamp >= '1730162616000000000') AND (timestamp <= '1730268878000000000')
GROUP BY traceID
ORDER BY span_count DESC
LIMIT 10
```

For second point, do let me know what you think should be the best approach for the same? I tested this query on approximately 200M traces and it perfromed as expected. Let me see, if we can optimise this query somehow.

**Comment by srikanthccv** [comment]
>If we need to finf the traces where 1000<spanCount<2000, that will go in the where clause.

Please share how this is achieved in the code.

> I tested this query on approximately 200M traces and it perfromed as expected

Please help me understand the performed as expected part. Have you folks discussed some pre-requisite in terms of resources needed and how you would have billions of traceIDs? From my experience, anything beyond 10 million rows in the group by questionable and beyond 25 mil is where the line should be drawn in most cases. Unless the enormous amount of memory availability, the 200M should have crashed with memory error.

**Comment by srikanthccv** [comment]
I don't think grouping by traceID at the query time is an option for us. I believe @nityanandagohain has created some summary tables as a part of traces v3, which helps specifically with count; please check with him once.

**Comment by eKuG** [comment]
```
SELECT
    traceID,
    COUNT() AS span_count,
    max(toInt64(timestamp) + durationNano) - min(toInt64(timestamp)) AS total_duration_nano
FROM signoz_traces.signoz_index_v2
WHERE (timestamp >= '1730162616000000000') AND (timestamp <= '1730268878000000000')
GROUP BY traceID
HAVING COUNT() > 5
ORDER BY span_count DESC
LIMIT 10
```

@srikanthccv According to the document I have written on notion, it should have been having instead of where for Span_count. 
Having said that, I understand your concern with group by clause with larger dataset. Let me start a conversation on slack with @nityanandagohain when he can add span_count MV on trace v3

**Comment by eKuG** [comment]
> I don't think grouping by traceID at the query time is an option for us. I believe @nityanandagohain has created some summary tables as a part of traces v3, which helps specifically with count; please check with him once.

**Pull request closed without merging**
