### PR TITLE
chore(query-service): update `GoValuateFuncs` definitions

### PR DESCRIPTION
**Pull request by prashant-shahi**
### Summary

- Fixed `now` function
- Remove `toUnixTimestamp` query-builder function which was breaking - we shall bring this back if the need arises for any customers for computing timestamp query with static date string values.

If you had any queries using `toUnixTimestamp(now())`, you can use `now()` instead.

#### Related Issues / PR's

Related to #4877

#### Affected Areas and Manually Tested Areas

Any query using `toUnixTimestamp` or `now`.

Signed-off-by: Prashant Shahi <prashant@signoz.io>

### CODE REVIEW

**Review by srikanthccv — APPROVED** [review]

**Comment by srikanthccv** [comment]
Since `A - now()` is not working. I don't think this will fix it because the error says mismatched data type.

**Comment by prashant-shahi** [comment]
yeah, this will not fix that issue.

**Comment by srikanthccv** [comment]
Please update the funtions `GoValuateFuncs["now"] ` and `GoValuateFuncs["toUnixTimestamp"]` to return a float64 value and check.

**Comment by prashant-shahi** [comment]
> Please update the funtions GoValuateFuncs["now"]  and GoValuateFuncs["toUnixTimestamp"] to return a float64 value and check.

I have done the exact same thing locally. Testing it now. 😄

**Review by srikanthccv — DISMISSED** [review]

**Review by srikanthccv — APPROVED** [review]

**Comment by prashant-shahi** [comment]
> 	GoValuateFuncs["toUnixTimestamp"] = func(args ...interface{}) (interface{}, error) {

@srikanthccv If the returned value always needs to `float64` for queries to work, can we update it to explicitly return the same?

**Pull request merged**
