### PR TITLE
feat: Error exception

### PR DESCRIPTION
**Pull request by palash-signoz**
Error and Error detail page is added

### CODE REVIEW

**Comment by pranshuchittora** [comment]
@palash-signoz 

https://user-images.githubusercontent.com/32242596/163532350-f3ce1082-7fe7-411b-a82a-3fb9aaa3d6b3.mov

**Comment by ankitnayan** [comment]
@makeavish @prashant-shahi please enable an env to review this PR. Also, should the redis errors from hotrod app be displayed in errors and exceptions page?

**Comment by prashant-shahi** [comment]
@ankitnayan we already have a test environment for this PR. Please got to `Errors` page and switch the duration to `Last 1 week`.

Here is the URL: http://54.242.164.227:3301/errors

Here are some remarks:
- Using hotrod application, we can observe errors only in traces, but not anywhere else.
- Using Microservice sample app, no errors are observed anywhere.
- week old Errors and Exceptions that can be seen were manually sent by @makeavish using a FlaskApp

**Review by pranshuchittora — APPROVED** [review]
Not able to see any errors on the page. So won't be able to review the PR from feature perspective. Did a quick code-review, code-wise looks good.

https://user-images.githubusercontent.com/32242596/164731502-b835a850-0219-442f-b55e-5bca3436c41c.mov

**Pull request merged**
