### PR TITLE
fix: where clause is updated

### PR DESCRIPTION
**Pull request by palashgdev**
where clause fixes for an operator like exist,nin,like,nlike
close https://github.com/SigNoz/signoz/issues/3682

### CODE REVIEW

**Review by nityanandagohain — CHANGES_REQUESTED** [review]
Upper case is not working now

* If I type `container_Id CONTAINS` then conten it still shows me operators instead of suggesting values
image

**Review by nityanandagohain — COMMENTED** [review]
Looks good to me.

@palashgdev  please create the issue where updating a old filter for has/nhas doesn't work

@srikanthccv can you also give this a look once ?

**Review by nityanandagohain — CHANGES_REQUESTED** [review]
It's breaking in dashboards page @palashgdev 

https://github.com/SigNoz/signoz/assets/26831659/d6a9f344-95bd-4195-9c21-c610be2d0b7a

**Comment by palashgdev** [comment]
@nityanandagohain https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded/50387233#50387233 we can ignore this error

**Review by nityanandagohain — DISMISSED** [review]

**Comment by srikanthccv** [comment]
superseded by https://github.com/SigNoz/signoz/pull/4379

**Pull request closed without merging**
