### PR TITLE
upgraded some deprecated packages

### PR DESCRIPTION
**Pull request by rkmdCodes**
I have upgraded the following deprecated packages  :-
.1) `visible` to `open`
.2) `onVisibleChange` to `onOpenChange`
I have changed the files as mentioned in #2360.I tried to resolve `overlay` to `menu` upgrade but I am getting the following error.
`(property) DropdownProps.menu?: MenuProps | undefined
Type 'ReactElement<any, any>' has no properties in common with type 'MenuProps'.ts(2559)
dropdown.d.ts(23, 5): The expected type comes from property 'menu' which is declared here on type 'IntrinsicAttributes & DropdownProps'`.
How should I go about resolving this?
Thanks

### CODE REVIEW

**Comment by rkmdCodes** [comment]
hi @makeavish , can you help me in resolving the overlay to menu depreacated error , I have already tried a few things but none seem to work, this issue is also raised on antd official repo `https://github.com/ant-design/ant-design/issues/38344`.
Thanks

**Comment by rkmdCodes** [comment]
hi @palashgdev bhaiya , can you help me in resolving the overlay to menu depreacated error , I have already tried a few things but none seem to work, this issue is also raised on antd official repo https://github.com/ant-design/ant-design/issues/38344.
Thanks

**Comment by palashgdev** [comment]
Hi @rkmdCodes 
Sure allow me some time

will get back to you

**Comment by techchintan** [comment]
Hi @rkmdCodes ,

Please visit [#2422](https://github.com/SigNoz/signoz/pull/2422) for your issue.

CC: @palashgdev

**Comment by rkmdCodes** [comment]
hi @palashgdev @techchintan  , I have made a new PR #2424 .
Thanks

**Pull request closed without merging**
