### PR TITLE
feat(FE): span Kind is added in the trace filter page

### PR DESCRIPTION
**Pull request by palashgdev**
part of https://github.com/SigNoz/signoz/issues/2192

### CODE REVIEW

**Review by makeavish — CHANGES_REQUESTED** [review]
After this change, an extra call is being made to getTagFilters API.

**Comment by makeavish** [comment]
GroupBy options need to fetch tag filters, please fix that

**Review by makeavish — APPROVED** [review]

**Review by srikanthccv — COMMENTED** [review]
Why does `getTagValues` not use the new `SpanKind` from the `TagFilterParams`?

**Comment by makeavish** [comment]
> Why does `getTagValues` not use the new `SpanKind` from the `TagFilterParams`?

That's because frontend changes have not been made for tagValue API, @palashgdev can we add spanKind to tagValue API too?

**Comment by srikanthccv** [comment]
If the API is supposed to consider the SpanKind, it should apply filtering on kind for TagValues request whether or not the frontend made code changes. It's generally good to view frontend as one of the clients consuming your API, but the API is written without a particular client in mind. I think the tag values should be filtered based on kind like the other attributes; then we missed it and maybe should focus on how/where a change affects.

**Review by makeavish — APPROVED** [review]

**Review by srikanthccv — APPROVED** [review]

**Pull request merged**
