### PR TITLE
fix(FE): Centered pagination for all tables since it was inaccessible due to chat icon hovering over it.

### PR DESCRIPTION
**Pull request by siddhantparekh**
### Why
Closing #553 

### What has changed
**Position of pagination component under the table**

### CODE REVIEW

**Review by aryanshridhar — COMMENTED** [review]
We use `yarn` instead of `npm`. Hence you can safely remove the `package-lock.json` file.

**Comment by pal-sig** [comment]
> We use `yarn` instead of `npm`. Hence you can safely remove the `package-lock.json` file.

@aryanshridhar i think we can force the use of yarn 

Could be a good starting point https://www.freecodecamp.org/news/how-to-force-use-yarn-or-npm/

as we are also using yarn in the docker images so we can safely use npm
cc: @ankitnayan

**Comment by aryanshridhar** [comment]
> @aryanshridhar i think we can force the use of yarn
> 
> Could be a good starting point https://www.freecodecamp.org/news/how-to-force-use-yarn-or-npm/

Sounds good!

**Comment by siddhantparekh** [comment]
> We use `yarn` instead of `npm`. Hence you can safely remove the `package-lock.json` file.

Should I remove that and create a new pull request?

**Comment by pal-sig** [comment]
Closing as discussion is still pending.. will re-open if matches the requirement

**Pull request closed without merging**
