### PR TITLE
fix: use severity_number to determine severity_text_type

### PR DESCRIPTION
**Pull request by DanikRaikhlin**
### Summary

Add .NET notations for SEVERITY_TEXT_TYPE and use them to fix log level coloring.

#### Related Issues / PR's

Issue : #4693

#### Screenshots

image

### CODE REVIEW

**Comment by srikanthccv** [comment]
Hello, I would solve this issue differently. I would use the `severity_number` to show the relevant colour schema for logs. This will work regardless of the severity text which can be an arbitrary string and varies from one system to another.

**Comment by DanikRaikhlin** [comment]
@srikanthccv I fully agree that would be a better solution, I'll adjust the PR.

**Comment by DanikRaikhlin** [comment]
PR updated to use severity_number

**Comment by srikanthccv** [comment]
LGTM, i'll let the owners of the code review it.

**Pull request closed without merging**
