### PR TITLE
feat(FE): dashboard alerts is added

### PR DESCRIPTION
**Pull request by palashgdev**
Close https://github.com/SigNoz/signoz/issues/3733

### CODE REVIEW

**Comment by palashgdev** [comment]
need to remove the apm to alerts changes as backend is not ready

**Review by Rajat-Dabade — DISMISSED** [review]
LGTM 🚀

**Comment by srikanthccv** [comment]
- When the user is creating the alert for the first time i.e no existing alert. Do not allow alert creation with an empty selected query 
- Invalid `api/v1/dashboards/` GET request polling is happening from alerts listing page

**Comment by srikanthccv** [comment]
- Dashboard can create multiple ClickHouse/PromQL queries but the alerts shows only one. We should show all the queries.

There are two queries here
Screenshot 2023-11-09 at 3 39 06 PM

**Comment by srikanthccv** [comment]
- Do not show create alerts for table panel type.

**Comment by srikanthccv** [comment]
@palashgdev these are the main issues that I could find in testing

**Comment by palashgdev** [comment]
Thanks @srikanthccv will take a look

**Comment by srikanthccv** [comment]
Let's wrap up this today

**Comment by palashgdev** [comment]
@srikanthccv 

1. fixed promql issue which we discussed offline
2. enabled the default selected which is enabled query as default option
3. for table panel widget create alert is not visible 

Screenshot 2023-11-10 at 9 37 42 PM

**Review by srikanthccv — DISMISSED** [review]

**Review by srikanthccv — APPROVED** [review]

**Review by YounixM — APPROVED** [review]

**Comment by YounixM** [comment]
@palashgdev : the down arrows next query names should be at the end of the row.

**Comment by palashgdev** [comment]
> @palashgdev : the down arrows next query names should be at the end of the row.

saw the comments seems like you are suggesting the design change
would recommend to change the figma then will change the design

**Pull request merged**
