### PR TITLE
chore: update .github/CODEOWNERS

### PR DESCRIPTION
**Pull request by srikanthccv**

### CODE REVIEW

**Comment by ankitnayan** [comment]
Maybe we should introduce folder wise owners in backend otherwise all 5-6 folks will be added as reviewer in every backend PR

**Review by prashant-shahi — APPROVED** [review]

**Comment by prashant-shahi** [comment]
@ankitnayan Shouldn't the backend related PRs be relevant for backend team to take a look at?

Perhaps not for `Makefile` and `.git*`,  however `query-service` and `go.*` should be okay backend team to look at.
And approve from their end to unblock the person.

**Comment by srikanthccv** [comment]
The folder approach is brittle. While some folders have specific logic, overall files are distributed over several folders containing various changes. And with the folder-wise assignment, when the owners make changes (usually the case), no one is assigned.

**Comment by srikanthccv** [comment]
Or I can remove the CODEOWNERS for query-serivce and let the PR authors select who they want to get reviews from. Let me know what you think.

**Comment by ankitnayan** [comment]
>let the PR authors select who they want to get reviews from

this looks good to me

**Comment by srikanthccv** [comment]
Updated

**Comment by srikanthccv** [comment]
@ankitnayan merge this. Let the author of PR select the reviewers for a change.

**Pull request merged**
