### PR TITLE
feat: date time picker improvements

### PR DESCRIPTION
**Pull request by vikrantgupta25**
### Summary

- added the ability to type the duration expression in the global time dropdown of the format `1 week/s , minute/s , hour/s, day/s` in the date time picker input 
- added the semi relative time options in the date time picker for faster filtering 

#### Related Issues / PR's

fixes https://github.com/SigNoz/signoz/issues/4321

fixes https://github.com/SigNoz/signoz/issues/4322

#### Screenshots

NA

### CODE REVIEW

**Review by srikanthccv — COMMENTED** [review]
Two minor issue https://www.loom.com/share/6d79a063386748e180938c7d4320424f

**Comment by vikrantgupta25** [comment]
@srikanthccv addressed the comments.

**Comment by srikanthccv** [comment]
Functionally LGTM. This is a good change but not an urgent one so please add tests.

**Comment by vikrantgupta25** [comment]
> This is a good change but not an urgent one so please add tests.

yes will merge this post adding the tests.

**Comment by vikrantgupta25** [comment]
closing this as too old! let's do it in a cleaner and better way

**Pull request closed without merging**
