### PR TITLE
fix: Move db calls to prepared statement for checkTTLStatusItem in clickhousereader

### PR DESCRIPTION
**Pull request by srikanth-iyengar**
Part of #1353
The is a part to solve umbrella issue for moving the db calls to prepared statements

### CODE REVIEW

**Comment by srikanth-iyengar** [comment]
Hey @srikanthccv can you PTAL?

**Comment by srikanthccv** [comment]
Please format the code

**Comment by srikanth-iyengar** [comment]
> Please format the code

PTAL I have formatted the code

**Comment by srikanth-iyengar** [comment]
Hey @srikanthccv I have updated branch up to date with the develop branch

**Review by srikanthccv — APPROVED** [review]

**Pull request merged**
