### PR TITLE
[Refactor]: css fixes

### PR DESCRIPTION
**Pull request by Rajat-Dabade**
Fixes: https://github.com/SigNoz/signoz/issues/4019

### CODE REVIEW

**Comment by YounixM** [comment]
Before and After screenshot.

**Comment by Rajat-Dabade** [comment]
Before

Screenshot 2023-12-27 at 4 33 02 PM

After: 

Screenshot 2023-12-27 at 4 33 31 PM

**Review by YounixM — APPROVED** [review]

**Comment by YounixM** [comment]
@Rajat-Dabade : Please add the after change screenshots.

**Comment by Rajat-Dabade** [comment]
Already added @YounixM 

> Before
> 
> Screenshot 2023-12-27 at 4 33 02 PM
> After:
> 
> Screenshot 2023-12-27 at 4 33 31 PM

**Pull request merged**
