### PR TITLE
fix(query builder): Better UI for filter on empty string in query builder

### LINKED ISSUE #3762: Better UI for filter on empty string in query builder
https://github.com/SigNoz/signoz/issues/3725#issuecomment-1759197459
image

### PR DESCRIPTION
**Pull request by joemiltonm**
Hi SigNoz team, 

The issue was to add double quotes to represent a empty string in the options in the query builder. 
To solve this, I've made changes to the chipValue variable. 
I've used useMemo hook to render the final options to be presented to the user. 

Resolves #3762

### CODE REVIEW

**Comment by YounixM** [comment]
@joemiltonm: Please add screenshots/screen recordings for before and after the change for faster review.

**Comment by joemiltonm** [comment]
> @joemiltonm: Please add screenshots/screen recordings for before and after the change for faster review.

Hi, below are the screenshots before change, without double quotes. 

Screenshot from 2023-11-02 09-05-32

Screenshot from 2023-11-02 09-05-46

below is the screencast after the change, with double quotes to represent no value. 
[Screencast from 02-11-23 09:24:55 AM IST.webm](https://github.com/SigNoz/signoz/assets/64725924/2fb2fa72-2302-48fd-86f0-354d992d226b)

**Comment by palashgdev** [comment]
@joemiltonm single quotes would fail while transforming into the value token

Screenshot 2023-12-01 at 4 13 09 PM

**Comment by makeavish** [comment]
@joemiltonm Please look into comments

**Comment by makeavish** [comment]
> > @joemiltonm Please look into comments
> 
> Hi @makeavish, sorry for the delay. will prioritize and fix this.

Thanks 🙏

**Pull request closed without merging**
