### PR TITLE
feat: metrics is renamed to services in sidebar

### PR DESCRIPTION
**Pull request by palashgdev**
Close https://github.com/SigNoz/signoz/issues/1249

### CODE REVIEW

**Review by pranshuchittora — COMMENTED** [review]
Can you pls check whether resource attributes works with this change or not

**Review by pranshuchittora — APPROVED** [review]

**Comment by pranay01** [comment]
@palashgdev Let's not change `Application` and the URLs in this release, though Pranshu makes valid points. We can pick in later release if needed.

We can capitalise first letters of Alerts and Dashboards though - as @pranshuchittora mentioned. I think it should be simple

**Comment by palashgdev** [comment]
>@palashgdev Let's not change Application and the URLs in this release, though Pranshu makes valid points. We can pick in later release if needed.

We can capitalise first letters of Alerts and Dashboards though - as @pranshuchittora mentioned. I think it should be simple

Yes we can pick in another one

**Comment by palashgdev** [comment]
> @palashgdev Let's not change `Application` and the URLs in this release, though Pranshu makes valid points. We can pick in later release if needed.
> 
> We can capitalise first letters of Alerts and Dashboards though - as @pranshuchittora mentioned. I think it should be simple

Alerts are already done https://github.com/SigNoz/signoz/pull/1268

raising pr for dashboard

**Pull request merged**
