### PR TITLE
Align the query start and end timestamps to the nearest multiple of step

### PR DESCRIPTION
**Pull request by srikanthccv**
Fixes https://github.com/SigNoz/signoz/issues/2825

### CODE REVIEW

**Review by makeavish — APPROVED** [review]
LGTM.
Please resolve conflicts and merge

**Comment by nityanandagohain** [comment]
This is still a relevant PR right ?

**Comment by srikanthccv** [comment]
It is still relevant. I don't think assumptions/logic is completely correct.

**Review by ankitnayan — APPROVED** [review]

**Comment by srikanthccv** [comment]
I need to fix a lot of tests; don't review yet.

**Comment by srikanthccv** [comment]
PTAL, This is ready now.

**Comment by srikanthccv** [comment]
Please review

**Review by nityanandagohain — APPROVED** [review]

**Comment by srikanthccv** [comment]
I am going to merge this since the only thing that changed since the last approvals is tests. You can still review it and I will respond to the comments.

**Pull request merged**
