### PR TITLE
fix: time is now grabbed from the global time

### LINKED ISSUE #587: BUG(FE): Span list shown has time outside the selected range
https://www.loom.com/share/e538a11dfe1e44fea056321f8f343062

### PR DESCRIPTION
**Pull request by palash-signoz**
This PR fixes #587

### CODE REVIEW

**Comment by pal-sig** [comment]
Need the dayjs branch so i have merged this branch 

cc: @pranay01

**Comment by pranay01** [comment]
When coming from application metrics page -> view traces -> trace filter page

I see the custom visualisation has -15 to +15 min of time when the point in application metrics pages where view traces was clicked. But date time filter only shows 1 min interval. Shouldn't this also show the time from -15 min to +15 min from time when view traces is clicked? As the span lists below also corresponds to that time

for the example in the screen shot - shouldn't time filter show 11:06 to 11:36? 

@ankitnayan Please confirm on this

Screenshot 2022-01-07 at 12 43 05 AM

**Comment by pranay01** [comment]
There is still some issue with this PR. Not working as expected - https://www.loom.com/share/1f7ca3ca82f34d9d90b1ad29fa0350ce

**Comment by palash-signoz** [comment]
Closing as this is not needed in the NEW UI

**Pull request closed without merging**
