### PR TITLE
feat: Error boundary is added in the app

### LINKED ISSUE #227: Bug:(FE) Handle unCaught Error in component
## Bug description
There is no fallback component when there is any unhandled Error in the React component

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Screenshot 2021-07-16 at 8 23 29 AM

## Expected behaviour

Component must be rendered to show a handful of errors and to show a useful message

## How to reproduce

1. in any component throw a new Error('any message')
2. screen may be black or white

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:

## Additional context
1. https://reactjs.org/docs/error-boundaries.html

### PR DESCRIPTION
**Pull request by palash-signoz**
This fixes #227

### CODE REVIEW

**Comment by pranay01** [comment]
@pal-sig What should I test in this PR?

**Comment by palash-signoz** [comment]
> > @pal-sig What should I test in this PR?
> 
> When there is unhandled error blank screen is showed to the user ... right now a error component is show to the user
below is the ref for the error component 

Screenshot 2022-01-27 at 2 31 00 PM

**Comment by ankitnayan** [comment]
@pranshuchittora please do a peer review

**Comment by pranay01** [comment]
Something not found UI page - https://www.figma.com/file/lE5BDDuulXuGnqvB5GRk1V/SigNoz-OSS---Design-System?node-id=2228%3A35237

**Comment by palash-signoz** [comment]
Closing as error component is updated which can be picked from another pr

**Pull request closed without merging**
