### PR TITLE
feat: add ability to import Grafana dashboards

### PR DESCRIPTION
**Pull request by srikanthccv**
This works for many dashboards with different versions. There will still be some JSON schemas in the wild that don't fit the struct and throw an error. It's impossible to handle them all, but this is tested with multiple versions from 6.4.3 to 9.2.0 and recognizes most of Prometheus' stuff.

Fixes https://github.com/SigNoz/engineering-pod/issues/793

https://www.loom.com/share/985fec014864401ea43646e4d192e18d

### CODE REVIEW

**Comment by pranay01** [comment]
Nice, I think this would be a very interesting feature

**Review by palashgdev — APPROVED** [review]
LGTM from FE

**Comment by ankitnayan** [comment]
- Can we standardise the size of panels for Grafana and just add panels with ordering? This would produce a much cleaner UI
- Some docs would be needed on using query in template variables. I would recommend avoiding the use of `labels_object` as that will not work for a distributed table

**Comment by ankitnayan** [comment]
It's great to see legend formatting and y-axis labels also being mapped

**Comment by srikanthccv** [comment]
>Can we standardise the size of panels for Grafana and just add panels with ordering? This would produce a much cleaner UI

Added the panels per row with equal size. They will be evenly arranged now in UI.

> Some docs would be needed on using query in template variables. I would recommend avoiding the use of labels_object as that will not work for a distributed table

Please take a look here https://deploy-preview-612--frosty-austin-928e43.netlify.app/docs/userguide/manage-variables/

and docs PR https://github.com/SigNoz/signoz.io/pull/612

**Review by ankitnayan — APPROVED** [review]

**Pull request merged**
