### PR TITLE
Explorer Toolbar maximised and minimised

### PR DESCRIPTION
**Pull request by Rajat-Dabade**
Fixes: https://github.com/SigNoz/signoz/issues/4647

https://github.com/SigNoz/signoz/assets/26198062/d403550c-417e-44d8-b334-a6c8675c98b6

### CODE REVIEW

**Comment by YounixM** [comment]
Screenshot 2024-03-22 at 5 34 09 PM

Need to improve light mode design

**Comment by YounixM** [comment]
This is also affecting the shortcut to collapse the sidebar, it's getting stuck.

**Comment by YounixM** [comment]
Screenshot 2024-03-22 at 5 49 51 PM


@Rajat-Dabade : Let's remove the drag feature and add the collapse button.

**Comment by Rajat-Dabade** [comment]
@YounixM Updated the description with the latest changes.

**Review by YounixM — APPROVED** [review]

**Review by Vikrant2520 — APPROVED** [review]

**Pull request merged**
