### PR TITLE
feat: add log explorer detail

### PR DESCRIPTION
**Pull request by yeshev**

### CODE REVIEW

**Review by nityanandagohain — CHANGES_REQUESTED** [review]
* If no data present in the selected time range then loading image should be removed.
* When we change the order by then the `id` filter used for pagination should be removed.

**Comment by nityanandagohain** [comment]
While adding new order by should the old ones appear as well ? @makeavish  @srikanthccv 
image

in this case level and method should not be present right ?

**Comment by nityanandagohain** [comment]
@yeshev can you resolve the conflicts

**Comment by yeshev** [comment]
> @yeshev can you resolve the conflicts
@nityanandagohain i've resolved

**Review by nityanandagohain — APPROVED** [review]

**Pull request merged**
