### PR TITLE
fix: changed versions of zookeeper & alertmanager

### PR DESCRIPTION
**Pull request by GermaVinsmoke**
Fixes a part of #2126 

## Changes

- Updated `signoz/alertmanager` to `latest` version as it was having the support of `linux/arm64`.
- Updated `bitnami/zookeeper` from `3.7.0` to `3.7.1` as it's having the support of `linux/arm64`.

After updating to these versions, it was not giving any warning in Apple M2. Not sure, if it's the correct version update but kept it to minor version update only to prevent any breaking change.

### CODE REVIEW

**Review by prashant-shahi — APPROVED** [review]
:shipit:  LGTM

**Comment by prashant-shahi** [comment]
@GermaVinsmoke Thanks for raising this PR.

**Comment by prashant-shahi** [comment]
@GermaVinsmoke could you please update all zookeeper versions from the same file (comments) as well as other docker-compose yaml files? Also, use `0.23.1` version for alertmanager.

- `deploy/docker/clickhouse-setup/docker-compose.yaml`
- `deploy/docker/clickhouse-setup/docker-compose-core.yaml`
- `deploy/docker-swarm/clickhouse-setup/docker-composey.yaml`
- `pkg/query-service/tests/test-deploy/docker-compose.yaml`

**Comment by GermaVinsmoke** [comment]
@prashant-shahi Hi
Can you check it again if it's all good or not? Updated the version of both things in all the listed files.

**Comment by srikanthccv** [comment]
>Sorry for those comment commits, completely forgot about those.
I believe, if everything's okay then can do squash and merge later on.


They will be squashed regardless.

**Review by prashant-shahi — APPROVED** [review]

**Review by srikanthccv — APPROVED** [review]

**Pull request merged**
