### PR TITLE
feat: trace v4 integration

### PR DESCRIPTION
**Pull request by nityanandagohain**
Have changes for
* Introduces new flag `use-trace-new-schema` , which when set true uses all the updated function for the new schema
* Using the flag it decides which query builder to use and which enrichment function to use.

----
* The only piece left after this is updating the TTL api's in query-service

---

Also please be more cautious and strict while reviewing this PR , thanks

FOR https://github.com/SigNoz/signoz/issues/5713

----

> [!IMPORTANT]
> Introduces `use-trace-new-schema` flag to enable new trace schema, updating APIs, models, and constants to support it.
> 
>   - **Behavior**:
>     - Introduces `use-trace-new-schema` flag in `api.go`, `server.go`, and `main.go` to toggle new trace schema.
>     - Updates `GetServicesList`, `SearchTracesV2`, `GetTraceAggregateAttributesV2`, `GetTraceAttributeKeysV2`, `GetTraceAttributeValuesV2`, `GetSpanAttributeKeysV2` to use new schema.
>     - Modifies telemetry functions `GetTotalSpans`, `GetSpansInLastHeartBeatInterval`, `GetTagsInfoInLastHeartBeatInterval` for new schema.
>   - **Models**:
>     - Adds `SearchSpanResponseItemV2` and `TraceSummary` to `response.go`.
>   - **Constants**:
>     - Updates `NewStaticFieldsTraces` and `DeprecatedStaticFieldsTraces` in `constants.go`.
>   - **Misc**:
>     - Updates `ThresholdRule` in `threshold_rule.go` to support new schema.
>     - Adjusts tests in `threshold_rule_test.go` for new schema.
>     - Minor changes in `logs.go` and `logs_test.go` for timestamp range handling.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=SigNoz%2Fsignoz&utm_source=github&utm_medium=referral)<sup> for c31e9cdda65e9b595e2653504c8bb701cd54d835. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by srikanthccv** [comment]
@nityanandagohain can you please sync with the latest develop changes?

**Comment by nityanandagohain** [comment]
Ignore this PR, I will create new ones.

**Comment by nityanandagohain** [comment]
I have updated this PR and synced with develop. Since the changes here are related to each other and easier to test, kept them in the same PR. Please let me know if a further breakdown is required.

**Comment by srikanthccv** [comment]
I won't be able to review 900+ changes in one PR. Please break it down.

**Review by srikanthccv — APPROVED** [review]
There is not much to review here. **Please throughly test**.

**Pull request merged**
