### PR TITLE
feat: add list and table views for logs

### PR DESCRIPTION
**Pull request by volodfast**
Close https://github.com/SigNoz/signoz/issues/1848

### CODE REVIEW

**Review by palashgdev — DISMISSED** [review]

**Review by palashgdev — DISMISSED** [review]

**Review by nityanandagohain — COMMENTED** [review]
- [x] Font of raw view should be changed.
- [ ] While hovering over a raw log line, I don't think a popup is expected or is it ?

**Review by nityanandagohain — COMMENTED** [review]
- [x] Convert interesting to selected field and vice versa, the table UI doesn't update. Have to manually refresh the page.

**Review by nityanandagohain — COMMENTED** [review]
- [x] In the table view, when I add many selected fields, to scroll horizontally I have to go down to the bottom of the page, which is not ideal experience
- [ ] Columns in table are not resizable in table view

**Comment by csudani7** [comment]
@palashgdev Please change from
	const draggableOpts = useMemo(
		() => ({
			enableUserSelectHack,
		}),
		[],
	);
to
       	const draggableOpts = useMemo(() => enableUserSelectHack, []);
       	
It causing error in terminal.

**Review by nityanandagohain — APPROVED** [review]
Looks good!

**Review by palashgdev — DISMISSED** [review]

**Review by palashgdev — APPROVED** [review]

**Pull request merged**
