### PR TITLE
feat: playwright is configured

### PR DESCRIPTION
**Pull request by palash-signoz**
Close https://github.com/SigNoz/signoz/issues/1142 playwright is configured

### CODE REVIEW

**Comment by pranay01** [comment]
@palash-signoz can you resolve the conflicts in this

**Comment by pranshuchittora** [comment]
Why are we testing the stagingapp ideally we should run the app `yarn dev` and then test `localhost:3301`

Screenshot 2022-05-20 at 13 42 05

**Review by pranshuchittora — APPROVED** [review]

**Review by pranshuchittora — APPROVED** [review]
LGTM

**Review by prashant-shahi — APPROVED** [review]
:shipit: LGTM

**Review by ankitnayan — APPROVED** [review]

**Pull request merged**
