### PR TITLE
fix: dot support in attribute name

### LINKED ISSUE #3553: [LOGS] Use materialized column if present for JSON search.
If user uses json key for search check if an attribute/materialized column is already present and then query based on that.

### PR DESCRIPTION
**Pull request by nityanandagohain**
### Summary

This PR adds the following support
* Proper formatting of attributes names with `.` in order by and group by
* In logs lines it doesn't return the `_` attributes.
* When a materialized column is created for an attribute with `.` in name it is replaced with `$$`. Eg:- `request.method` becomes `attribute_string_request$$method`
* Doesn't return the duplicate underscore attributes in the getFields API
* For checking exists we used indexOf(attr, key) > 0. Replaced it with has(attr, key) to make it consistant.
* For update fields endpoint use `default` instead of materialzied

#### Related Issues / PR's

Fixes #3553 

please look at https://github.com/SigNoz/signoz-otel-collector/pull/233 first

clickhouse migration : https://github.com/SigNoz/signoz-db-migrations/pull/8

Frontend changes required for this release https://github.com/SigNoz/signoz/issues/3681

### Tested
* For both index and non indexed values with and without dot in name
  * filtering
  * group by 
  * order by is working
  * Formulas are working
* Enrichment of queries are working fine
* json queries are working as expected with no interference
* limit queries

### Blast radius
* Alerts and Dhashboards and saved filters
* If in any of the above the attribute name was actually containing `.` it must be updated within a month else it will start failing.

### CODE REVIEW

**Comment by srikanthccv** [comment]
Test the formulas once.

**Comment by nityanandagohain** [comment]
Have tested for formulas.

Also update the code to change the update fields fuctions to use Default instead of materialized.

**Comment by srikanthccv** [comment]
Can you add a test for formula query?

**Comment by nityanandagohain** [comment]
Thanks, @srikanthccv , yeah I tested only filters along with formulas, when testing in a group by it broke. Have fixed and added a test as well.

**Comment by srikanthccv** [comment]
LGTM now; I can't of think any other case where it can fail. I will take another look and approve.

**Comment by nityanandagohain** [comment]
Thanks, appreciate it

**Review by srikanthccv — APPROVED** [review]
Please check time series chart dot attribute names with a limit applied once. Otherwise LGTM

**Comment by nityanandagohain** [comment]
Yeah, right that got left out , have fixed it

**Review by srikanthccv — APPROVED** [review]

**Comment by pranay01** [comment]
Merged based on Nitya's request

**Pull request merged**
