### PR TITLE
[Refactor]: added tag for data type and type of logs

### PR DESCRIPTION
**Pull request by Rajat-Dabade**
Close https://github.com/SigNoz/signoz/issues/3300

### CODE REVIEW

**Review by nityanandagohain — APPROVED** [review]
LGTM

**Review by nityanandagohain — APPROVED** [review]

**Review by YounixM — APPROVED** [review]

**Review by palashgdev — APPROVED** [review]
LGTM

**Comment by nityanandagohain** [comment]
was this reverted @YounixM  @Rajat-Dabade , the changes are not present.

**Comment by Rajat-Dabade** [comment]
@nityanandagohain I am able to see it staging. Not sure where are not able to see these changes.

cc: @YounixM 

Screenshot 2023-11-30 at 12 50 59 PM

**Comment by nityanandagohain** [comment]
Hey @Rajat-Dabade sorry it was a mistake , i mistook this for https://github.com/SigNoz/signoz/issues/3299

**Pull request merged**
