### PR TITLE
Change time range in api call of Service Map to 1 min from latest 

### PR DESCRIPTION
**Pull request by dhrubesh**
https://github.com/SigNoz/signoz/issues/92

### CODE REVIEW

**Review by ankitnayan — COMMENTED** [review]
Change 1-day option from datetimepicker to 5 mins. So, we shall have 2 options only.
1. 1-min
2. 5-min

**Review by ankitnayan — COMMENTED** [review]
The options in Metrics tab seem to be tampered.
Screenshot 2021-05-15 at 7 22 46 PM

**Comment by dhrubesh** [comment]
> The options in Metrics tab seem to be tampered.
> Screenshot 2021-05-15 at 7 22 46 PM

@ankitnayan this is fixed, could you check again?

**Review by ankitnayan — COMMENTED** [review]
https://www.loom.com/share/ac903597d36f42d8b84ad65b73ad1849

**Review by ankitnayan — APPROVED** [review]

**Pull request merged**
