### PR TITLE
feat: add support for changing the font size in logs

### PR DESCRIPTION
**Pull request by vikrantgupta25**
### Summary

this PR adds the support to change the font size to `small` / `medium` / `large` in the logs explorer pages 

Design :- https://github.com/SigNoz/engineering-pod/issues/1205#issuecomment-1953604809
```
Small : font size - 11px; line height - 16px; padding - 1px;
Medium : font size - 13px; line height - 20px; padding - 1px;
Large : font size - 14px; line height - 24px; padding 2px;
```

#### Related Issues / PR's

fixes -  https://github.com/SigNoz/engineering-pod/issues/1205 

contributes to - https://github.com/SigNoz/signoz/issues/5169

#### Screenshots

https://github.com/user-attachments/assets/f0a8d331-7b0b-4997-84e0-768a03cb9810

### CODE REVIEW

**Comment by GeekBoySupreme** [comment]
@vikrantgupta25 can we decrease the padding/spacing between the lines by 2-4px when the font is small? Looks like a lot of space there rn.

**Comment by vikrantgupta25** [comment]
> can we decrease the padding/spacing between the lines by 2-4px when the font is small? Looks like a lot of space there rn.

done @GeekBoySupreme

**Comment by GeekBoySupreme** [comment]
Looks good.

**Comment by ankitnayan** [comment]
default to small?

**Comment by vikrantgupta25** [comment]
> default to small?

this will only be for the first time user opens the page, after that whatever the user selects will be stored as a preference and used subsequently, Kept the default medium so that once this is deployed users shouldn't feel a sudden jerk of reduced size. 

can change it to small if you think otherwise. cc @ankitnayan

**Comment by ankitnayan** [comment]
I want to keep small as default since many users have asked to reduce size already. I want to see this in staging though before confirmation. If video is good enough proxy, I am okay with small size

**Comment by vikrantgupta25** [comment]
> I want to keep small as default since many users have asked to reduce size already. I want to see this in staging though before confirmation. If video is good enough proxy, I am okay with small size

okay , reduced the default to small rather than medium ✅

**Comment by YounixM** [comment]
@vikrantgupta25 : We need to centralize the decisions related to styles we have taken for this change.

let's collate all the style changes for small / medium / large as PR comment so that we have documentation for the same whenever want to loop back to this.

**Review by YounixM — APPROVED** [review]

**Pull request merged**
