### PR TITLE
fix: empty string search doesn't return all exceptions

### PR DESCRIPTION
**Pull request by YounixM**
### Summary

1. Search is not working as expected in the Exceptions tab, empty results showing after removing the search word
-->Search any keyword (ex: prod) in the Application under the Exceptions tab
-->Remove the above keyword then search

### CODE REVIEW

**Comment by makeavish** [comment]
When the server is not responding then we just see the loading screen, we should see the server error page as you described above.

Screenshot 2024-01-09 at 10 29 23

**Comment by YounixM** [comment]
@vishalsharma1800 : Did we get a 5xx response in the above case ?

**Comment by makeavish** [comment]
> @vishalsharma1800 : Did we get a 5xx response in the above case ?

Wrong vishal BTW.

We get `ERR_NAME_NOT_RESOLVED` without any response code.

**Review by Rajat-Dabade — COMMENTED** [review]
Added some non-blocking comments.

Test:
Search in exception - Application - works fine. 
Server Error flow - discuss with @makeavish and @YounixM

**Review by Rajat-Dabade — DISMISSED** [review]
LGTM 👍

**Review by Vikrant2520 — DISMISSED** [review]

**Review by Rajat-Dabade — APPROVED** [review]

**Review by Vikrant2520 — APPROVED** [review]

**Review by makeavish — APPROVED** [review]

**Pull request merged**
