### PR TITLE
Used Prepared Statements for GetChannel in clickhousereader

### PR DESCRIPTION
**Pull request by jshiwam**
Added prepared statements for GetChannel(id string).

### CODE REVIEW

**Comment by makeavish** [comment]
@jshiwam How prepared statements are useful here? 
They can be useful for mutation of table/db but not sure how they are useful here.

**Comment by jshiwam** [comment]
@makeavish yes you are right in this case it is not that useful. What I understood from the issue is that any query that uses an args needs to be moved to prepared statement. If this is not required then I will remove it and make the other changes.

**Comment by makeavish** [comment]
Got it, I didn't see the issue: https://github.com/SigNoz/signoz/issues/1353
Linked it.

**Review by srikanthccv — COMMENTED** [review]
Using transaction here seems like an unnecessarily complication to me. You would generally use transaction for in case of mutation like `CREATE`, `UPDATE` etc...

**Review by srikanthccv — COMMENTED** [review]
The change can something simple like this.

```
stmt, err := r.localDB.Preparex(`SELECT id, created_at, updated_at, name, type, data data FROM notification_channels WHERE id=?`)
err = stmt.Get(&channel, idInt)
```

**Comment by jshiwam** [comment]
Yeah I was not sure whether to use transactions or not but used it in this case. Will make the changes and submit the PR.

**Comment by jshiwam** [comment]
@srikanthccv made the suggested changes. Please confirm. I might have to squash the commits. Did some rebasing and resolved many conflicts.

**Review by srikanthccv — APPROVED** [review]

**Pull request merged**
