### PR TITLE
fix: fixed all not deselecting and empty array setting to _ALL_

### PR DESCRIPTION
**Pull request by SagarRajput-7**
### Summary

Fixed:
- Deselecting `All` not working
- Deselecting a single value was setting is to `All` 

#### Screenshots

https://github.com/user-attachments/assets/00e961c2-bafc-47e2-9ca2-5c1de85638cc

#### Affected Areas and Manually Tested Areas

- tested dashboard variable with all selection

### CODE REVIEW

**Comment by srikanthccv** [comment]
@SagarRajput-7, please tackle the dropdown closing first. A user wants to deselect ALL so they can select something. If the dropdown closes right away without letting them select values, it's very annoying and makes the whole benefit of deselect least useful.

**Comment by SagarRajput-7** [comment]
> @SagarRajput-7, please tackle the dropdown closing first. A user wants to deselect ALL so they can select something. If the dropdown closes right away without letting them select values, it's very annoying and makes the whole benefit of deselect least useful.

@srikanthccv - That is also in progress, please check this - https://github.com/SigNoz/signoz/pull/6087


https://github.com/user-attachments/assets/81fed029-c052-4e8c-b420-ee2f755573f3

**Review by YounixM — APPROVED** [review]

**Comment by YounixM** [comment]
Please confirm that this is the expected behaviour.

**Comment by ahmadshaheer** [comment]
@SagarRajput-7, as I checked, deselecting a single item (if I click on the option title), selects all the checkboxes. I was wondering if this is expected

https://www.loom.com/share/4761450e448f418283498995d5bf89be

**Comment by SagarRajput-7** [comment]
> @SagarRajput-7, as I checked, deselecting a single item (if I click on the option title), selects all the checkboxes. I was wondering if this is expected
> 
> https://www.loom.com/share/4761450e448f418283498995d5bf89be

Yes, if you see, while selecting the option title we show a `All` text also there, hence it is expected to select all there.
Basically we have two options there - `All` and `Only`

**Review by ahmadshaheer — APPROVED** [review]

**Pull request merged**
