### PR TITLE
feat: group by severity logs explorer page by default 

### PR DESCRIPTION
**Pull request by vikrantgupta25**
### Summary

- the list view has by default group by of severity text for frequency chart. 
- no change in any other existing behavviour 

#### Related Issues / PR's

fixes https://github.com/SigNoz/signoz/issues/4727

#### Screenshots

https://github.com/user-attachments/assets/a1d92fb5-b3f0-4ed7-8a98-b597ba1aaeae

#### Affected Areas and Manually Tested Areas

- Logs Explorer Views Chart 
- Live Logs Chart

### CODE REVIEW

**Comment by ankitnayan** [comment]
Please report the perf impact on scanning 50M or 100M rows

**Comment by vikrantgupta25** [comment]
> Please report the perf impact on scanning 50M or 100M rows

https://www.notion.so/signoz/group-by-severity_text-78339feea9914f1c839f01f999904ad9 added the cases for 100M and 450M here.

**Comment by ankitnayan** [comment]
>no legends for the logs explorer frequency chart as the colors are self explanatory.

This is only relevant when the groupby is `severity_text`. The legends are important if the groupby clause is something else like `k8s.deployment.name`

**Comment by ankitnayan** [comment]
I am still of the opinion of showing legends of different `severity_text` as there is no coloring convention and users might get confused with `warning, debug` and `error, fatal` categories.

**Comment by ankitnayan** [comment]
Also, a loom along with the PR helps a lot in seeing visual changes and 1st set of feedbacks without needing to run the PR

**Comment by vikrantgupta25** [comment]
> This is only relevant when the groupby is severity_text. The legends are important if the groupby clause is something else like k8s.deployment.name

The frequency chart has a fixed group by of `severity_text` always hence the no legends for the same. 

> I am still of the opinion of showing legends of different severity_text as there is no coloring convention and users might get confused with warning, debug and error, fatal categories.

We can do the same, also on the hover of the graph you will be able to see the details of label and the corresponding color. 


> Also, a loom along with the PR helps a lot in seeing visual changes and 1st set of feedbacks without needing to run the PR

yes i just removed the older video and was about to add the updated changes video soon before sharing it in channel 😅

**Comment by GeekBoySupreme** [comment]
Looks good to me @vikrantgupta25

**Comment by nityanandagohain** [comment]
> The where clause and all the filters for the lower graph are picked and aggregateOperator and groupBy are overridden by Count and SeverityText respectively

will it help the user in some way when they are already doing groupby some other field ?
We can keep this functionality limited to the list view ?

**Comment by vikrantgupta25** [comment]
> We can keep this functionality limited to the list view ?

done @nityanandagohain , added back the legends as well to make sure users don't get confused due to no standard color encodings.

**Review by nityanandagohain — APPROVED** [review]

**Review by YounixM — APPROVED** [review]

**Pull request merged**
