### PR TITLE
BUG: refresh button is now fixed

### LINKED ISSUE #574: FullView `Refresh` button within Dashboard panel isn't working.
## Bug description

While working on another issue I came up with this bug as - The `Refresh` button within a specific dashboard (when in FullView) isn't working as expected.

## Expected behavior
The application metric should refresh which would update the graph.

## Screenshot
Screenshot 2021-12-29 at 10 50 50 PM

(The `Refresh` button on upper top right corner should update the metrics)

## How to reproduce

1. Navigate to any application in dashboard.
2. Click on the `FullView` icon to view the graph in a dedicated modal.
3. Click the refresh button.

## Version information 
* **Signoz version**: 0.5.4
* **Browser version**: 95.0.2 (64-bit)
* **Your OS and version**: macOS Monterey 12.1

### PR DESCRIPTION
**Pull request by palash-signoz**
This issue fixes #574

### CODE REVIEW

**Review by pranay01 — APPROVED** [review]
Works fine from a functionality perspective

**Comment by ybettan** [comment]
@ankitnayan enforcing `ok-to-test` label isn't merge yet https://github.com/SigNoz/signoz/pull/596

**Comment by ybettan** [comment]
@pal-sig can you please rebase this PR on new `main` so it picks the updated CI?

**Comment by pal-sig** [comment]
> @pal-sig can you please rebase this PR on new `main` so it picks the updated CI?

done @ybettan

**Pull request merged**
