### PR TITLE
fix: Logs issues are fixed

### PR DESCRIPTION
**Pull request by palashgdev**
Close https://github.com/SigNoz/engineering-pod/issues/827
Close https://github.com/SigNoz/signoz/issues/1713
Close https://github.com/SigNoz/signoz/issues/1688
Close https://github.com/SigNoz/engineering-pod/issues/849
Close https://github.com/SigNoz/engineering-pod/issues/848

### CODE REVIEW

**Comment by pranay01** [comment]
@palashgdev facing this issue https://www.loom.com/share/e1bc96cb0bb54ac1906293d1468947d1

**Comment by pranay01** [comment]
@palashgdev Rather than `AND` taking a new line, it should be in the same line as the operator as shown in the current version screenshot.
Screenshot 2022-11-21 at 2 38 33 PM

**Comment by pranay01** [comment]
@ankitnayan Please test #827 I am not sure that the issue was
@palashgdev Need more details on https://github.com/SigNoz/engineering-pod/issues/849

**Comment by ankitnayan** [comment]
LGTM wrt https://github.com/SigNoz/engineering-pod/issues/827

**Review by ankitnayan — APPROVED** [review]

**Pull request merged**
