### PR TITLE
refactor: fill span for full view and dashboard view

### PR DESCRIPTION
**Pull request by Rajat-Dabade**
Loom: https://www.loom.com/share/60eb35809cee4bfca867f4b1ca39e548?sid=2e24ff77-28ad-45fe-90dd-d9567fa4ff64

Fixes: https://github.com/SigNoz/signoz/issues/4377

### CODE REVIEW

**Comment by YounixM** [comment]
@Rajat-Dabade : In the video shared above, the graph seems incomplete and the global time option is center aligned. Can you check and update the latest screenshots please.

**Comment by Rajat-Dabade** [comment]
@YounixM This was because I have updated the response for the query-range manually. Also, the global time is in full view in the centre because this branch was cut before that fix.

**Review by Vikrant2520 — APPROVED** [review]

**Comment by YounixM** [comment]
Can you please verify once? We will do a release post this.

**Review by YounixM — APPROVED** [review]

**Comment by Rajat-Dabade** [comment]
Re-verified: https://www.loom.com/share/2e7e49fa26ea46e1b142936d5b7c3ff4?sid=0de241a5-1e1e-4e40-b627-2aafbdb30713

cc; @YounixM

**Pull request merged**
