### PR TITLE
Fixing issue #6124

### PR DESCRIPTION
**Pull request by Sanidhyafeaturist**
In this pull request I have done:

Removed Unused Imports: Cleaned up any unnecessary imports or commented-out code to maintain readability.

Consolidated Tests: Ensured all test cases are organized within a single describe block, making it easier to read and manage.

Comments and Structure: Maintained a consistent structure and clear commenting within the test cases for better understanding.

### CODE REVIEW

**Comment by Sanidhyafeaturist** [comment]
In this pull request I have done:

Removed Unused Imports: Cleaned up any unnecessary imports or commented-out code to maintain readability.

Consolidated Tests: Ensured all test cases are organized within a single describe block, making it easier to read and manage.

Comments and Structure: Maintained a consistent structure and clear commenting within the test cases for better understanding.

**Comment by srikanthccv** [comment]
Stop spamming!

**Comment by Sanidhyafeaturist** [comment]
> Stop spamming!

wdym?

**Comment by Sanidhyafeaturist** [comment]
why you closed my pull request?

**Comment by srikanthccv** [comment]
Because this is neither fixing the said issue nor adding anything meaningful. My liberal interpretation of the change is you put the code in some LLM and pasted the output it gave without really knowing what it was supposed to do. I also noticed very random answers on issues without any idea of the implication of those suggestions here https://github.com/SigNoz/signoz/issues/6100.

**Comment by srikanthccv** [comment]
I took a quick look your recent pull requests and it seems you did similar stuff in other repos https://github.com/goatshriek/stumpless/pull/460. Please don't do this.

**Pull request closed without merging**
