### PR TITLE
feat: hide aggregate every for table view

### PR DESCRIPTION
**Pull request by yeshev**

### CODE REVIEW

**Comment by makeavish** [comment]
Please remove Aggregation Interval text for table view as well
Screenshot 2023-07-06 at 12 44 41

**Comment by makeavish** [comment]
This seems unrelated to this PR:
Here `count` column should have value, instead of `A`
Screenshot 2023-07-06 at 13 45 06

**Comment by yeshev** [comment]
> This seems unrelated to this PR: Here `count` column should have value, instead of `A` Screenshot 2023-07-06 at 13 45 06

@makeavish fixed

**Review by makeavish — APPROVED** [review]

**Comment by nityanandagohain** [comment]
Why is this merged into `feat/list_infinity_scroll` @makeavish  ?

**Comment by makeavish** [comment]
@yeshev Are you merging all branches to `feat/list_infinity_scroll`?

**Pull request merged**
