### PR TITLE
feat: ability to clone a panel

### LINKED ISSUE #707: Ability to Clone a Panel
## Is your feature request related to a problem? No

When setting up Panels it would be nice to have the ability to `Clone` a panel when adding lots of similar metrics. 

## Describe the solution you'd like

A `Clone this Panel` button from the Dashboard as one of the action buttons on the panel on right top. This will immediately clone the panel and also take you to the Edit mode of the new panel.

### PR DESCRIPTION
**Pull request by gitstart**
Fixes #707 

## Demo
https://www.loom.com/share/0a19db7c24454924a7c875e9d901a6cf

---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.

### CODE REVIEW

**Comment by palashgdev** [comment]
Hello, @gitstart 

thank you raising the PR.

rather than providing a clone widget option on the widget page

would it be feasible to add option to the widget header(`src/container/GridGraphLayout/WidgetHeader`)? (only visible for editor and admin permission)

PS: You can use the menu's Copy icon.

**Comment by gitstart** [comment]
> Hello, @gitstart
> 
> thank you raising the PR.
> 
> rather than providing a clone widget option on the widget page
> 
> would it be feasible to add option to the widget header(`src/container/GridGraphLayout/WidgetHeader`)? (only visible for editor and admin permission)
> 
> PS: You can use the menu's Copy icon in the menu

Thank you for the review @palashgdev. We are working on it

**Comment by palashgdev** [comment]
@gitstart can you please check the number of changes seems like there is some issue

**Review by palashgdev — APPROVED** [review]

**Comment by srikanthccv** [comment]
I commented on an earlier PR, which appears to be doing the same https://github.com/SigNoz/signoz/pull/2646. Are these two same?

**Comment by palashgdev** [comment]
> I commented on an earlier PR, which appears to be doing the same #2646. Are these two same?

was not aware of #2646 @gitstart can you please confirm?

**Comment by gitstart** [comment]
> > I commented on an earlier PR, which appears to be doing the same #2646. Are these two same?
> 
> was not aware of #2646 @gitstart can you please confirm?

No, these are not the same. #2646 is for cloning an Alert and this PR is for cloning a Panel. cc: @palashgdev @srikanthccv

**Review by makeavish — APPROVED** [review]

**Pull request merged**
