### PR TITLE
[DO NOT MERGE BEFORE #609] ci: removing the redundant 'build-pipeline' workflow

### PR DESCRIPTION
**Pull request by ybettan**
Signed-off-by: Yoni Bettan <ybettan@redhat.com>

### CODE REVIEW

**Comment by prashant-shahi** [comment]
@ybettan We will need this to verify that builds are successful for the **_frontend_** and **_query-service_**.
Yes, you are right, these steps will happen again, but only after the `ok-to-test` label for k3s test cluster.

Let me know if you think otherwise.

**Comment by ybettan** [comment]
@prashant-shahi, the ok-to-test is relevant only for PRs check, it is not pushing any image.

I have pushed an updated push workflow https://github.com/ybettan/signoz/blob/main/.github/workflows/push.yaml that will build and push multi-arch images to dockerhub when new commit reaches `main` or release branches.

The old flow contains non-used images (flattener for example) and doesn't build for multi arch.

I think this PR should be re-opened.

**Comment by prashant-shahi** [comment]
I agree with you take on it. However, the trigger in `push.yaml` is from push to `main` branch and `v**` tags.
While `build.yaml` is for verifying `frontend` and `query-service` builds of the incoming PRs,
If it passes `build` workflow, we can decide to add the `ok-to-test` label.

**Pull request closed without merging**
