### PR TITLE
feat: #1524 refresh button bug fix

### PR DESCRIPTION
**Pull request by vg18gupta**
https://github.com/Signoz/signoz/issues/1524

### CODE REVIEW

**Comment by palashgdev** [comment]
@vg18gupta can you please check build if failing maybe you can fix it by running `lint:fix`

**Comment by vg18gupta** [comment]
@palashgdev made the lint fixes.

**Comment by palashgdev** [comment]
Thanks @vg18gupta :-D

**Review by palashgdev — APPROVED** [review]
LGTM

**Pull request merged**
