### PR TITLE
feat: limit & order by is enabled in the metrics query builder

### PR DESCRIPTION
**Pull request by palashgdev**
Close https://github.com/SigNoz/signoz/issues/3389

### CODE REVIEW

**Comment by srikanthccv** [comment]
@palashgdev we need order by also.

**Comment by palashgdev** [comment]
> @palashgdev we need order by also.
but the issue says limit only ... but let me update orderBy also

**Comment by palashgdev** [comment]
@srikanthccv updated

**Comment by srikanthccv** [comment]
I tested this and it's working for time series. I need to update some backend logic for table panel type.

**Review by srikanthccv — APPROVED** [review]

**Pull request merged**
