### PR TITLE
feat: tree is updated to show different node values instead of editor

### PR DESCRIPTION
**Pull request by palashgdev**
Close https://github.com/SigNoz/signoz/issues/3530

### CODE REVIEW

**Comment by nityanandagohain** [comment]
@palashgdev 

https://github.com/SigNoz/signoz/assets/26831659/f558dfd0-89a8-4b9d-9291-161df9a9ccc8

**Comment by palashgdev** [comment]
https://github.com/SigNoz/signoz/assets/88981777/9f05c4d6-43c0-4a40-888a-3bd4b551dedf

@nityanandagohain not applicable

**Review by nityanandagohain — APPROVED** [review]

**Review by Rajat-Dabade — APPROVED** [review]
LGTM 🚀

**Review by YounixM — APPROVED** [review]

**Comment by ankitnayan** [comment]
Can we expand all the nodes using `defaultExpandAll` prop of the tree component?

**Comment by palashgdev** [comment]
> Can we expand all the nodes using `defaultExpandAll` prop of the tree component?

this message missed while merging ... addressing in new pr

**Pull request merged**
