### PR TITLE
feat(alerts): add telegram alert channel

### PR DESCRIPTION
**Pull request by Ellipse0934**
### Summary

Add telegram alert channel. PR once completed must be merged with https://github.com/SigNoz/alertmanager/pull/28 

#### Related Issues / PR's

https://github.com/SigNoz/signoz/issues/4700

### CODE REVIEW

**Comment by srikanthccv** [comment]
@Ellipse0934 great progress 🎉

**Comment by Ellipse0934** [comment]
On the one hand its "almost" done, I can successfully add a telegram channel and receive messages. Currently no message templating is exposed to the user but its a good feature to have regardless. So I think it's better to have a template defined with the deceiver so the user can set it. We can possibly defer this for another PR if you want or we can start here.

I did accidentally break something, It was working. But now I only get a notification when I change/save the config. Subsequent alerts are sent from query-service to alertmanager but something is failing and the failure is silent. In a way its good because it may likely point to a fragile part and save someone trouble in the future.

There is also the issue of HTML escape. It's not being done correctly. I need to fix this on the alertmanager PR.

Previews: 
image
image

**Comment by Ellipse0934** [comment]
1. I was confused about how alerting worked and thought that alert was fired continuously. There was no issue so ignore the previous comment.
2. Bug with parsemode is fixed. Now the telegram message is correctly sent and rendered as per telegram styling entities.

Let me know if you need any help reviewing. You'll need to create a telegram bot. Instructions for that can be found here: https://core.telegram.org/bots/tutorial

**Comment by developerisnow** [comment]
guys can't wait hearings from you @YounixM , @srikanthccv ! Telegram integration doesn't work for newcomer as me

**Comment by srikanthccv** [comment]
This missed my radar. @Ellipse0934 do you want to continue the work?

**Comment by Ellipse0934** [comment]
No. This was working when I marked it for review. I had pinged on the community slack too but received no response.

Quite likely that this will work if you resolve the conflicts.

**Comment by srikanthccv** [comment]
@developerisnow if you would like to see Telegram integration, you are free to take over this PR work and create a separate PR.

**Pull request closed without merging**
