### PR TITLE
fix(FE): removed time filter from settings page #374

### PR DESCRIPTION
**Pull request by Mohmn**

### CODE REVIEW

**Comment by pal-sig** [comment]
hi @Mohmn 
Thanks for raising the PR 
would it possible that we have a array of routes in which top nav is not shown

**Comment by Mohmn** [comment]
@pal-sig sure I can declare it, should I declare the array routes **(in which top nav is not show )** in the constants/routes file.
and should I use that array to conditionally render the  **time filter** component.

**Comment by pal-sig** [comment]
Hi @Mohmn 
Can we have that array over the component only ?

**Review by pal-sig — APPROVED** [review]

**Review by ankitnayan — APPROVED** [review]

**Comment by ankitnayan** [comment]
solves #374

**Pull request merged**
