### PR TITLE
Uplot time range

### PR DESCRIPTION
**Pull request by YounixM**
### Summary

https://www.loom.com/share/a7ae45e7c7d542c492d536eec0bf58f5?sid=69594ad8-8950-476e-b31e-9261cfcfa4b0

#### Affected Areas and Manually Tested Areas

Dashboard
Full View
Widget Edit Mode
Services
Traces Explorer
Logs Explorer
Alerts

Widget Time Preference

image
Screenshot 2023-12-13 002050
Screenshot 2023-12-13 002102

close: https://github.com/SigNoz/signoz/pull/4144#issuecomment-1838201978
close: https://github.com/SigNoz/signoz/issues/4194

### CODE REVIEW

**Comment by YounixM** [comment]
Screenshot 2023-12-04 at 4 09 27 PM

**Review by Rajat-Dabade — DISMISSED** [review]
LGTM

**Review by Rajat-Dabade — APPROVED** [review]

**Comment by srikanthccv** [comment]
@YounixM let me know if this https://signoz-team.slack.com/archives/C02TJ466H8U/p1701944371613659?thread_ts=1701860411.877149&cid=C02TJ466H8U is fixed so that I can test again.

**Comment by YounixM** [comment]
Sure @srikanthccv

**Comment by YounixM** [comment]
@srikanthccv: have updated the code to handle widget time preference.

**Review by Rajat-Dabade — APPROVED** [review]

**Review by palashgdev — APPROVED** [review]

**Comment by srikanthccv** [comment]
You may not notice it for large intervals (>= 1hr) but for smaller intervals it's clearly visible.

**Comment by srikanthccv** [comment]
It's the data problem from the backend. However, I think we should revert this for now and merge back when the things are sorted out.

**Pull request merged**
