### PR TITLE
feat: added info funct for panels in dashaboard layout for showing description

### PR DESCRIPTION
**Pull request by SagarRajput-7**
### Summary

Added icon next to title - which on hover will show the description added under the dashboard

#### Related Issues / PR's

https://github.com/SigNoz/signoz/issues/5788

#### Screenshots

https://github.com/user-attachments/assets/36d68e30-1147-463c-8aba-da72baa8922d

#### Affected Areas and Manually Tested Areas

- tested different dashboard panels
- service page, as these also use widgetHeader component

----

> [!IMPORTANT]
> Adds an info icon in `WidgetHeader` to display widget descriptions using a tooltip with new styles for long descriptions.
> 
>   - **Behavior**:
>     - Adds an info icon in `WidgetHeader` to display widget descriptions using a tooltip.
>     - Tooltip is shown only if `widget.description` is present.
>   - **Styles**:
>     - Adds `.long-tooltip` and `.info-tooltip` classes in `WidgetHeader.styles.scss` to style the tooltip for long descriptions.
>     - Updates `.widget-header-title-container` to accommodate the info icon.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=SigNoz%2Fsignoz&utm_source=github&utm_medium=referral)<sup> for b005e0304442cd48e9a74c8bad66a66b53599aa8. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by vikrantgupta25** [comment]
check the case where there is an error / warning from the API call. how does all of this things fit together ? can you please add screenshots for these scenarios ?

**Comment by SagarRajput-7** [comment]
> check the case where there is an error / warning from the API call. how does all of this things fit together ? can you please add screenshots for these scenarios ?

Yes @vikrantgupta25 , they fit well - 
image

image

**Comment by vikrantgupta25** [comment]
> Yes @vikrantgupta25 , they fit well -

see the issue of same icon for warning and description.

**Comment by vikrantgupta25** [comment]
>  icon get's weirdly nested when there are errors and loading

we need to place it better, either next to table panel and stick it here. or somewhere else where its explicitly available.

**Comment by SagarRajput-7** [comment]
> > icon get's weirdly nested when there are errors and loading
> 
> we need to place it better, either next to table panel and stick it here. or somewhere else where its explicitly available.

image

**Comment by vikrantgupta25** [comment]
FYI @GeekBoySupreme

**Review by vikrantgupta25 — DISMISSED** [review]

**Comment by vikrantgupta25** [comment]
@SagarRajput-7 do verify the services page once if things are looking as expected there as well. the same component is used in services page as well.

**Review by vikrantgupta25 — APPROVED** [review]

**Review by YounixM — APPROVED** [review]

**Pull request merged**
