### PR TITLE
Feat(UI): toggle tabs is updated in the setting tab

### PR DESCRIPTION
**Pull request by palash-signoz**
* Toggle Tab Component is updated
* There is no need for the redux in the tab routing

### CODE REVIEW

**Comment by pranay01** [comment]
@pal-sig What should I test here?

**Comment by palash-signoz** [comment]
> @pal-sig What should I test here?

In the Settings Page
each tab will have different route and while we refresh state will persist

**Comment by pranay01** [comment]
Working fine with staging app as backend
https://www.loom.com/share/4c9bb2aa0dc749a9aee00d6c4a0ec85d

**Comment by palash-signoz** [comment]
> Working fine with staging app as backend, But not sure what is the change compared to current version deployed in stagingapp.signoz.io @palash-signoz stagingapp.signoz.io also has different URLs for different tabs and states are preserved

Remove the state from the redux.. as kept in the local

**Comment by pranay01** [comment]
@palash-signoz What are the functional changes here and what should I test?

**Comment by pranay01** [comment]
There's no change from functional perspective. More of a refactoring

**Review by pranay01 — APPROVED** [review]

**Pull request merged**
