### PR TITLE
fix(FE): eslint

### PR DESCRIPTION
**Pull request by nidhi-tandon**

### CODE REVIEW

**Comment by rahulrana95** [comment]
@nidhi-tandon  package-lock file is deleted?

**Comment by nidhi-tandon** [comment]
> @nidhi-tandon package-lock file is deleted?

Yes because we are using yarn.

**Comment by palashgdev** [comment]
> > @nidhi-tandon package-lock file is deleted?
> 
> Yes because we are using yarn.

@nidhi-tandon can we show an error if we are using npm?

**Comment by nidhi-tandon** [comment]
> > > @nidhi-tandon package-lock file is deleted?
> > 
> > 
> > Yes because we are using yarn.
> 
> @nidhi-tandon can we show an error if we are using npm?

Will do this in the following PR

**Comment by palash-signoz** [comment]
Hi @nidhi-tandon 
There are a few pointers and suggestion

1. Eslint is somehow not working properly with prettier (the only single-quote rule is not working fine attaching the screenshot)
1. Can we make two scripts one linting `eslint . --debug` and another one for eslint:fix `eslint . --debug --fix`
1. can we have .eslintignore file in which we can ignore files we don't want (like build,node_modules..etc)
Screenshot 2021-08-17 at 12 13 44 PM

**Comment by palash-signoz** [comment]
Hi, can we use this [package](https://www.npmjs.com/package/eslint-plugin-simple-import-sort)

Do let me know your thoughts on this one

**Comment by nidhi-tandon** [comment]
How are you running it? On hitting `save`?  @palash-signoz 

> Eslint is somehow not working properly with prettier (the only single-quote rule is not working fine attaching the screenshot)

**Comment by nidhi-tandon** [comment]
How would this help? 🤔 

> Can we make two scripts one linting eslint . --debug

**Comment by nidhi-tandon** [comment]
Sure. We can add that. Currently we are running eslint on `src` with file extensions `.tsx`, `.js`, `.jsx`. Lmk if `.eslintignore` is still required.

> can we have .eslintignore file in which we can ignore files we don't want (like build,node_modules..etc)

**Comment by nidhi-tandon** [comment]
Yes, we can use this. Let's add this in the following PR. 

>  Hi, can we use this package

**Comment by palash-signoz** [comment]
> How are you running it? On hitting `save`? @palash-signoz
> 
> > Eslint is somehow not working properly with prettier (the only single-quote rule is not working fine attaching the screenshot)

Yes using the autoSave feature and triggering eslint on save

**Comment by palash-signoz** [comment]
> How would this help? 🤔
> 
> > Can we make two scripts one linting eslint . --debug

Possible it will run in the root of the frontend and will print all the things (what different rule eslint is trying to grab and which file it is running on)...after all user does not have to wait to see the results

**Comment by palash-signoz** [comment]
> Sure. We can add that. Currently we are running eslint on `src` with file extensions `.tsx`, `.js`, `.jsx`. Lmk if `.eslintignore` is still required.
> 
> > can we have .eslintignore file in which we can ignore files we don't want (like build,node_modules..etc)

just thinking what if we have scripts that may not be placed under `src` (possibly in future)

**Comment by ankitnayan** [comment]
@palash-signoz @nidhi-tandon If we don't need this PR we can close this. What say?

**Comment by palash-signoz** [comment]
> @palash-signoz @nidhi-tandon If we don't need this PR we can close this. Or is it under change?

yes, we don't need this PR.

**Pull request closed without merging**
