### PR TITLE
ci: Adding 'e2e' GH workflows.

### PR DESCRIPTION
**Pull request by ybettan**
The flow contains of multiple steps:

    * build 'query-service' and 'frontend' images and push them to the image registry
    * deploy a disposable k3s cluster
    * deploy the app on the cluster
    * set a tunnel to allow accessing the UI from the web browser

Signed-off-by: Yoni Bettan <ybettan@redhat.com>

### CODE REVIEW

**Comment by ybettan** [comment]
This PR is blocked by https://github.com/SigNoz/signoz/pull/578

**Comment by ybettan** [comment]
Hold with that PR, I will make some changes to it.
Setting WIP.

**Review by prashant-shahi — APPROVED** [review]
LGTM  :shipit:

**Pull request merged**
